# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-26 01:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NightlyRunTracker',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'nightly_run_tracker',
                'managed': True,
            },
        ),
    ]
