# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-26 02:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queuehandler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nightlyruntracker',
            name='run_type',
            field=models.CharField(default='1', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
