# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-13 07:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('roommanager', '0002_auto_20170305_1727'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('job_type', models.CharField(choices=[(b'MACHINE PURCHASE', b'MACHINE PURCHASE'), (b'MACHINE REPAIR', b'MACHINE REPAIR'), (b'MACHINE INSTALLATION', b'MACHINE INSTALLATION'), (b'PLUMBING', b'PLUMBING'), (b'ELECTRICAL WORK', b'ELECTRICAL WORK')], max_length=255)),
                ('status', models.CharField(choices=[(b'CREATED', b'CREATED'), (b'IN PROGRESS', b'IN_PROGRESS'), (b'CLOSED', b'CLOSED')], max_length=255)),
                ('start_date', models.DateField()),
                ('final_date', models.DateField(null=True)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('laundry_room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='roommanager.LaundryRoom')),
                ('machine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='roommanager.Machine')),
            ],
            options={
                'db_table': 'job',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='LineItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('line_item_type', models.CharField(choices=[(b'LABOR', b'LABOR'), (b'PART', b'PART')], max_length=255)),
                ('status', models.CharField(choices=[(b'CREATED', b'CREATED'), (b'IN PROGRESS', b'IN_PROGRESS'), (b'CLOSED', b'CLOSED')], max_length=255)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('start_date', models.DateField(null=True)),
                ('finish_date', models.DateField(null=True)),
                ('time', models.IntegerField(blank=True, null=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='expensetracker.Job')),
            ],
            options={
                'db_table': 'line_item',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Technician',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('employment_type', models.CharField(choices=[(b'CONTRACTOR', b'CONTRACTOR'), (b'EMPLOYEE', b'EMPLOYEE')], max_length=255)),
                ('hourly_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'technician',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='lineitem',
            name='technician',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='expensetracker.Technician'),
        ),
    ]
