# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-05-19 14:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expensetracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('MACHINE PURCHASE', 'MACHINE PURCHASE'), ('MACHINE REPAIR', 'MACHINE REPAIR'), ('MACHINE INSTALLATION', 'MACHINE INSTALLATION'), ('PLUMBING', 'PLUMBING'), ('ELECTRICAL WORK', 'ELECTRICAL WORK')], max_length=255),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('CREATED', 'CREATED'), ('IN PROGRESS', 'IN_PROGRESS'), ('CLOSED', 'CLOSED')], max_length=255),
        ),
        migrations.AlterField(
            model_name='lineitem',
            name='line_item_type',
            field=models.CharField(choices=[('LABOR', 'LABOR'), ('PART', 'PART')], max_length=255),
        ),
        migrations.AlterField(
            model_name='lineitem',
            name='status',
            field=models.CharField(choices=[('CREATED', 'CREATED'), ('IN PROGRESS', 'IN_PROGRESS'), ('CLOSED', 'CLOSED')], max_length=255),
        ),
        migrations.AlterField(
            model_name='technician',
            name='employment_type',
            field=models.CharField(choices=[('CONTRACTOR', 'CONTRACTOR'), ('EMPLOYEE', 'EMPLOYEE')], max_length=255),
        ),
    ]
