# Generated by Django 3.1 on 2021-05-15 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roommanager', '0102_auto_20210515_1410'),
        ('expensetracker', '0002_auto_20200519_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='laundry_room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='roommanager.laundryroom'),
        ),
        migrations.AlterField(
            model_name='job',
            name='machine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='roommanager.machine'),
        ),
        migrations.AlterField(
            model_name='lineitem',
            name='job',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='line_items', to='expensetracker.job'),
        ),
        migrations.AlterField(
            model_name='lineitem',
            name='technician',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='expensetracker.technician'),
        ),
    ]
