# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-05 16:57
from __future__ import unicode_literals

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InDbConfig',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('integer_value', models.IntegerField(blank=True, null=True)),
                ('float_value', models.FloatField(blank=True, null=True)),
                ('boolean_value', models.NullBooleanField()),
                ('string_field', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'in_db_config',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='InDbConfigType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('display_name', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'db_table': 'in_db_config_type',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='LaundryFascardUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=1000, null=True)),
                ('addr_1', models.CharField(blank=True, max_length=1000, null=True)),
                ('addr_2', models.CharField(blank=True, max_length=1000, null=True)),
                ('city', models.CharField(blank=True, max_length=200, null=True)),
                ('state', models.CharField(blank=True, max_length=200, null=True)),
                ('zip', models.CharField(blank=True, max_length=200, null=True)),
                ('mobile_phone', models.CharField(blank=True, max_length=200, null=True)),
                ('office_phone', models.CharField(blank=True, max_length=200, null=True)),
                ('email_address', models.CharField(blank=True, max_length=1000, null=True)),
                ('comments', models.CharField(blank=True, max_length=1000, null=True)),
                ('language', models.CharField(blank=True, max_length=200, null=True)),
                ('notify_cycle_complete', models.CharField(blank=True, max_length=200, null=True)),
                ('fascard_creation_date', models.DateTimeField(blank=True, null=True)),
                ('fascard_last_activity_date', models.DateTimeField(blank=True, null=True)),
                ('balance', models.FloatField(blank=True, null=True)),
                ('bonus', models.FloatField(blank=True, null=True)),
                ('discount', models.FloatField(blank=True, null=True)),
                ('free_starts', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=200, null=True)),
                ('is_employee', models.NullBooleanField()),
                ('loyalty_points', models.FloatField(blank=True, null=True)),
                ('ballance_spent', models.FloatField(blank=True, null=True)),
                ('bonus_spent', models.FloatField(blank=True, null=True)),
                ('free_starts_spent', models.FloatField(blank=True, null=True)),
                ('reload_method', models.FloatField(blank=True, null=True)),
                ('reload_balance', models.FloatField(blank=True, null=True)),
                ('reload_bonus', models.FloatField(blank=True, null=True)),
                ('cash_spent', models.FloatField(blank=True, null=True)),
                ('credit_card_spent', models.FloatField(blank=True, null=True)),
                ('user_group_id', models.IntegerField(blank=True, null=True)),
                ('last_location_id', models.IntegerField(blank=True, null=True)),
                ('xxx_caution_fascard_user_id', models.IntegerField(blank=True, null=True)),
                ('fascard_user_account_id', models.IntegerField()),
                ('coupons', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'laundry_fascard_user',
                'managed': True,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='LaundryGroup',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('display_name', models.CharField(max_length=200, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.CharField(max_length=8000)),
            ],
            options={
                'db_table': 'laundry_group',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='LaundryRoom',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('display_name', models.CharField(max_length=200, unique=True)),
                ('fascar_code', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('time_zone', models.CharField(choices=[(b'US/Eastern', b'US/Eastern'), (b'US/Western', b'US/Western')], max_length=255)),
                ('laundry_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roommanager.LaundryGroup')),
            ],
            options={
                'db_table': 'laundry_room',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('machine_type', models.IntegerField(choices=[(-1, b'UNKNOWN'), (0, b'WASHER'), (1, b'DRYER')])),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('make', models.CharField(blank=True, max_length=200, null=True)),
                ('machine_text', models.CharField(blank=True, max_length=200, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('machine_description', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'db_table': 'machine',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MachineSlotMap',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roommanager.Machine')),
            ],
            options={
                'db_table': 'machine_slot_map',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('web_id', models.CharField(max_length=100)),
                ('web_display_name', models.CharField(max_length=100)),
                ('clean_web_display_name', models.CharField(default='xxxx', max_length=100)),
                ('idle_cutoff_seconds', models.FloatField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_run_time', models.DateTimeField(blank=True, null=True)),
                ('slot_type', models.CharField(choices=[(b'STANDARD', b'STANDARD'), (b'DOUBLE', b'DOUBLE')], default=b'STANDARD', max_length=100)),
                ('laundry_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roommanager.LaundryRoom')),
            ],
            options={
                'db_table': 'slot',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='machineslotmap',
            name='slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roommanager.Slot'),
        ),
        migrations.AddField(
            model_name='laundryfascarduser',
            name='laundry_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roommanager.LaundryGroup'),
        ),
        migrations.AddField(
            model_name='indbconfig',
            name='in_db_config_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roommanager.InDbConfigType', unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='slot',
            unique_together=set([('laundry_room', 'web_id')]),
        ),
        migrations.AlterUniqueTogether(
            name='laundryroom',
            unique_together=set([('laundry_group', 'fascar_code')]),
        ),
    ]
