# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-14 00:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roommanager', '0002_auto_20170305_1727'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laundryfascarduser',
            name='laundry_group',
        ),
        migrations.DeleteModel(
            name='LaundryFascardUser',
        ),
    ]
