# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-06-09 17:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roommanager', '0003_auto_20170414_0033'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='laundrygroup',
            options={'managed': True, 'ordering': ['display_name']},
        ),
        migrations.AlterModelOptions(
            name='laundryroom',
            options={'managed': True, 'ordering': ['display_name']},
        ),
        migrations.AlterModelOptions(
            name='slot',
            options={'managed': True, 'ordering': ['laundry_room__display_name', 'web_display_name']},
        ),
    ]
