# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-04-28 16:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roommanager', '0004_auto_20170609_1744'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fascard_id', models.IntegerField()),
                ('machine_text', models.TextField()),
                ('machine_type', models.IntegerField(choices=[(-1, b'UNKNOWN'), (0, b'WASHER'), (1, b'DRYER')])),
                ('laundry_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roommanager.LaundryGroup')),
            ],
            options={
                'db_table': 'equipment_type',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='machine',
            name='equipment_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='roommanager.EquipmentType'),
        ),
    ]
