# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2019-07-08 11:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roommanager', '0005_auto_20180428_1658'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='equipmenttype',
            unique_together=set([('fascard_id', 'laundry_group')]),
        ),
    ]
