# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-15 15:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roommanager', '0006_auto_20190708_1122'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slot',
            old_name='web_id',
            new_name='slot_fascard_id',
        ),
        migrations.AlterUniqueTogether(
            name='slot',
            unique_together=set([('laundry_room', 'slot_fascard_id')]),
        ),
    ]
