# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-15 15:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roommanager', '0007_auto_20190815_1513'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slot',
            old_name='slot_type',
            new_name='equipment_start_check_method',
        ),
    ]
