# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-15 16:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roommanager', '0008_auto_20190815_1552'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slot',
            old_name='equipment_start_check_method',
            new_name='slot_type',
        ),
    ]
