# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-09-03 09:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roommanager', '0010_equipmenttype_equipment_start_check_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laundryroom',
            name='time_zone',
            field=models.CharField(choices=[(b'US/Eastern', b'US/Eastern'), (b'US/Western', b'US/Western')], default=b'US/Eastern', max_length=255),
        ),
    ]
