# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-10-29 14:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roommanager', '0012_auto_20191006_0855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot',
            name='laundry_room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='roommanager.LaundryRoom'),
        ),
    ]
