# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-11-03 10:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roommanager', '0013_auto_20191029_1436'),
        ('roommanager', '0012_auto_20191002_1704'),
    ]

    operations = [
    ]
