# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-11-28 09:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roommanager', '0014_merge_20191103_1028'),
        ('roommanager', '0014_machinemeter'),
    ]

    operations = [
    ]
