# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-11-28 15:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roommanager', '0015_merge_20191128_0933'),
    ]

    operations = [
        migrations.CreateModel(
            name='FailedSlotMachinePairing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('err_msg', models.CharField(max_length=200)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
