# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-11-28 15:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roommanager', '0016_failedslotmachinepairing'),
    ]

    operations = [
        migrations.AddField(
            model_name='failedslotmachinepairing',
            name='submission_id',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='failedslotmachinepairing',
            name='err_msg',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
