# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-11-28 16:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roommanager', '0018_auto_20191128_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='failedslotmachinepairing',
            name='tech_employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='roommanager.TechnicianEmployeeProfile'),
        ),
    ]
