# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-12-07 09:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roommanager', '0019_failedslotmachinepairing_tech_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='failedslotmachinepairing',
            name='tech_employee',
        ),
        migrations.DeleteModel(
            name='FailedSlotMachinePairing',
        ),
    ]
