# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-12-07 09:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roommanager', '0020_auto_20191207_0947'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlotMachinePairing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_id', models.CharField(blank=True, max_length=60, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('fascard_reader_code', models.CharField(max_length=100)),
                ('asset_code', models.CharField(max_length=100)),
                ('data_matrix_string', models.CharField(max_length=10)),
                ('valid', models.BooleanField(default=False)),
                ('err_msg', models.CharField(blank=True, max_length=200, null=True)),
                ('notification_sent', models.BooleanField(default=False)),
                ('tech_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='roommanager.TechnicianEmployeeProfile')),
            ],
        ),
    ]
