# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-12-07 11:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roommanager', '0021_slotmachinepairing'),
    ]

    operations = [
        migrations.AddField(
            model_name='slotmachinepairing',
            name='tech_jotform_username',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
