# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-12-07 12:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roommanager', '0022_slotmachinepairing_tech_jotform_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='slotmachinepairing',
            name='slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='roommanager.Slot'),
        ),
    ]
