# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-12-19 19:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roommanager', '0023_slotmachinepairing_slot'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slotmachinepairing',
            old_name='tech_jotform_username',
            new_name='codereadr_username',
        ),
        migrations.RenameField(
            model_name='technicianemployeeprofile',
            old_name='jotform_username',
            new_name='codereadr_id',
        ),
        migrations.AddField(
            model_name='machine',
            name='asset_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='machine',
            name='upkeep_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
