# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-12-22 21:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roommanager', '0026_auto_20191220_1754'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardReaderAsset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_reader_tag', models.CharField(max_length=50)),
                ('first_scan_time', models.DateTimeField(auto_now_add=True)),
                ('last_scan_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='HardwareBundlePairing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codereadr_username', models.CharField(blank=True, max_length=60, null=True)),
                ('submission_id', models.CharField(blank=True, max_length=60, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('fascard_reader_code', models.CharField(max_length=100)),
                ('asset_code', models.CharField(max_length=100)),
                ('data_matrix_string', models.CharField(max_length=10)),
                ('valid', models.BooleanField(default=False)),
                ('err_msg', models.CharField(blank=True, max_length=200, null=True)),
                ('notify', models.BooleanField(default=False)),
                ('notification_sent', models.BooleanField(default=False)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='roommanager.LaundryRoom')),
                ('slot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='roommanager.Slot')),
                ('tech_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='roommanager.TechnicianEmployeeProfile')),
            ],
        ),
        migrations.RemoveField(
            model_name='slotmachinepairing',
            name='slot',
        ),
        migrations.RemoveField(
            model_name='slotmachinepairing',
            name='tech_employee',
        ),
        migrations.DeleteModel(
            name='SlotMachinePairing',
        ),
    ]
