# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-01-01 12:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roommanager', '0032_auto_20191223_2028'),
    ]

    operations = [
        migrations.CreateModel(
            name='HardwareBundleRequirement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('hardware_type', models.CharField(choices=[('SLOT', 'SLOT'), ('MACHINE', 'MACHINE'), ('CARD_READER', 'CARD_READER')], max_length=100)),
                ('hardware_id', models.IntegerField()),
                ('done', models.BooleanField(default=False)),
            ],
        ),
    ]
