# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-01-07 08:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roommanager', '0033_hardwarebundlerequirement'),
    ]

    operations = [
        migrations.AddField(
            model_name='hardwarebundle',
            name='bundle_type',
            field=models.CharField(blank=True, choices=[('STACKDRYER', 'STACKDRYER'), ('SINGLE', 'SINGLE')], default='SINGLE', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='machine',
            name='asset_code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
