# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-04-14 18:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roommanager', '0037_auto_20200414_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='machineslotmap',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
