# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-05-04 10:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roommanager', '0039_remove_machineslotmap_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='placeholder',
            field=models.BooleanField(default=True),
        ),
    ]
