# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-05-21 10:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roommanager', '0041_auto_20200514_1407'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machinemeter',
            name='machine_slot_map',
        ),
        migrations.AddField(
            model_name='machinemeter',
            name='machine',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='roommanager.Machine'),
        ),
        migrations.AlterField(
            model_name='machinemeter',
            name='start_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
