# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-05-21 19:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roommanager', '0043_machinemeter_upkeep_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hardwarebundlepairing',
            name='data_matrix_string',
            field=models.CharField(max_length=40),
        ),
    ]
