# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-05-22 18:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roommanager', '0044_auto_20200521_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hardwarebundle',
            name='bundle_type',
            field=models.CharField(blank=True, choices=[('STACKDRYER', 'STACKDRYER'), ('SINGLE', 'SINGLE'), ('WAREHOUSE', 'WAREHOUSE')], default='SINGLE', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='hardwarebundlepairing',
            name='card_reader_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='hardwarebundlepairing',
            name='data_matrix_string',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='hardwarebundlepairing',
            name='scan_type',
            field=models.CharField(blank=True, choices=[('STACKDRYER', 'STACKDRYER'), ('SINGLE', 'SINGLE'), ('WAREHOUSE', 'WAREHOUSE')], max_length=20, null=True),
        ),
    ]
