# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-05-24 17:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roommanager', '0045_auto_20200522_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='hardwarebundle',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warehouse', to='roommanager.LaundryRoom'),
        ),
        migrations.AddField(
            model_name='hardwarebundlepairing',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pairing_warehouse', to='roommanager.LaundryRoom'),
        ),
    ]
