# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-06-26 12:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roommanager', '0046_auto_20200524_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardreaderasset',
            name='condition',
            field=models.CharField(blank=True, choices=[('new', 'new'), ('refurbished', 'refurbished')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cardreaderasset',
            name='make_model',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='cardreaderasset',
            name='serial',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cardreaderasset',
            name='status',
            field=models.CharField(blank=True, choices=[('available', 'available'), ('bundled', 'bundled')], default='available', max_length=20, null=True),
        ),
    ]
