# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-06-26 16:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roommanager', '0047_auto_20200626_1247'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cardreaderasset',
            old_name='make_model',
            new_name='model',
        ),
    ]
