# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-06-26 19:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roommanager', '0048_auto_20200626_1602'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('laundry_room', models.ForeignKey(help_text='Default location for card readers', on_delete=django.db.models.deletion.CASCADE, to='roommanager.LaundryRoom')),
            ],
        ),
    ]
