# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-06-26 21:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roommanager', '0049_defaultroom'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardreaderasset',
            name='upkeep_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
