# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-07-02 12:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roommanager', '0050_cardreaderasset_upkeep_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardReaderMeter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('upkeep_id', models.CharField(blank=True, max_length=50, null=True)),
                ('transactions_counter', models.PositiveIntegerField(default=0)),
                ('machine', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meter', to='roommanager.Machine')),
            ],
        ),
    ]
