# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-07-02 13:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roommanager', '0052_auto_20200702_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machinemeter',
            name='machine',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meter', to='roommanager.Machine'),
        ),
    ]
