# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-07-02 19:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roommanager', '0053_auto_20200702_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='technicianemployeeprofile',
            name='upkeep_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
