# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-07-05 20:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roommanager', '0055_hardwarebundlerequirement_assigned_technician'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardreaderasset',
            name='condition',
            field=models.CharField(blank=True, choices=[('new', 'new'), ('refurbished', 'refurbished')], default='new', max_length=20, null=True),
        ),
    ]
