# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-07-13 21:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roommanager', '0056_auto_20200705_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardreaderasset',
            name='condition',
            field=models.CharField(blank=True, choices=[('new', 'new'), ('refurbished', 'refurbished'), ('unknown', 'unknown')], default='unknown', max_length=20, null=True),
        ),
    ]
