# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-07-23 15:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roommanager', '0057_auto_20200713_2143'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValidTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_string', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddIndex(
            model_name='validtag',
            index=models.Index(fields=['tag_string'], name='roommanager_tag_str_d943c3_idx'),
        ),
    ]
