# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-08-22 17:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roommanager', '0061_equipmenttypeschedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmenttypeschedule',
            name='equipment_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roommanager.EquipmentType'),
        ),
    ]
