# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-09-17 20:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roommanager', '0063_workorderpart'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorderrecord',
            name='parts',
            field=models.ManyToManyField(to='roommanager.WorkOrderPart'),
        ),
    ]
