# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-10-02 21:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roommanager', '0065_laundryroommeter'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetMapOut',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_type', models.CharField(choices=[('SLOT', 'SLOT'), ('MACHINE', 'MACHINE'), ('CARD_READER', 'CARD_READER')], max_length=100)),
                ('asset_id', models.IntegerField()),
                ('status', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
