# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-10-04 22:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roommanager', '0068_assetmapout_needs_rescaning'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assetmapout',
            old_name='needs_rescaning',
            new_name='needs_rescanning',
        ),
    ]
