# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-10-05 21:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roommanager', '0069_auto_20201004_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='validtag',
            name='tag_string',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
