# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-11-07 21:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roommanager', '0070_auto_20201005_2130'),
    ]

    operations = [
        migrations.AddField(
            model_name='laundryroom',
            name='latitude',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='laundryroom',
            name='longitude',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
