# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-11-26 11:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roommanager', '0071_auto_20201107_2121'),
    ]

    operations = [
        migrations.CreateModel(
            name='HardwareBundleChangesLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hardware_type', models.CharField(blank=True, choices=[('SLOT', 'SLOT'), ('MACHINE', 'MACHINE'), ('CARD_READER', 'CARD_READER')], max_length=30, null=True)),
                ('old_piece_hardware_id', models.IntegerField(blank=True, null=True)),
                ('new_piece_hardware_id', models.IntegerField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('change_type', models.CharField(choices=[('SLOT_CHANGE', 'SLOT_CHANGE'), ('MACHINE_CHANGE', 'MACHINE_CHANGE'), ('CARD_READER_CHANGE', 'CARD_READER_CHANGE')], max_length=30)),
                ('new_bundle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='new_bundle', to='roommanager.HardwareBundle')),
                ('old_bundle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='old_bundle', to='roommanager.HardwareBundle')),
                ('technician', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='roommanager.TechnicianEmployeeProfile')),
            ],
        ),
    ]
