# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-12-28 11:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roommanager', '0075_auto_20201219_0957'),
    ]

    operations = [
        migrations.AddField(
            model_name='hardwarebundlerequirement',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
