# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2021-01-03 11:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roommanager', '0076_hardwarebundlerequirement_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='hardwarebundlepairing',
            name='combostack',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='equipmenttype',
            name='machine_type',
            field=models.IntegerField(choices=[(-1, 'UNKNOWN'), (0, 'WASHER'), (1, 'DRYER'), (3, 'COMBO_STACK')]),
        ),
        migrations.AlterField(
            model_name='machine',
            name='machine_type',
            field=models.IntegerField(choices=[(-1, 'UNKNOWN'), (0, 'WASHER'), (1, 'DRYER'), (3, 'COMBO_STACK')]),
        ),
    ]
