# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2021-01-04 13:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roommanager', '0077_auto_20210103_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorderrecord',
            name='available_in_api',
            field=models.BooleanField(default=True),
        ),
    ]
