# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2021-01-09 13:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roommanager', '0079_auto_20210104_1924'),
    ]

    operations = [
        migrations.CreateModel(
            name='BundleChangeApproval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('change_type', models.CharField(choices=[('SLOT_CHANGE', 'SLOT_CHANGE'), ('MACHINE_CHANGE', 'MACHINE_CHANGE'), ('CARD_READER_CHANGE', 'CARD_READER_CHANGE')], max_length=50)),
                ('approved', models.BooleanField(default=False)),
                ('approved_timestamp', models.DateTimeField()),
                ('previous_bundle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roommanager.HardwareBundle')),
                ('scan_pairing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roommanager.HardwareBundlePairing')),
            ],
        ),
    ]
