# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2021-01-09 18:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roommanager', '0080_bundlechangeapproval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bundlechangeapproval',
            name='approved_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
