# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2021-01-10 15:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roommanager', '0081_auto_20210109_1844'),
    ]

    operations = [
        migrations.CreateModel(
            name='OprhanedPieceRequiredAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(blank=True, choices=[('warehouse', 'Warehouse'), ('office', 'Office'), ('brooklyn', 'Brooklyn Office'), ('other-room', 'Another Laundry Room'), ('other-slot-same-room', 'Another Slot in the same Room'), ('disposed', 'Being Disposed'), ('sold', 'Sold'), ('manufacturer', 'Returning to Manufactureer'), ('abandoned', 'Abandoned on Site')], max_length=50, null=True)),
                ('hbr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roommanager.HardwareBundleRequirement')),
            ],
        ),
    ]
