# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2021-01-10 19:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roommanager', '0083_auto_20210110_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetmapout',
            name='scan_asset_tag',
            field=models.TextField(blank=True, null=True),
        ),
    ]
