# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2021-01-10 19:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roommanager', '0084_assetmapout_scan_asset_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetmapout',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
