# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2021-01-10 20:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roommanager', '0085_assetmapout_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetmapout',
            name='assigned_technician',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='roommanager.TechnicianEmployeeProfile'),
        ),
        migrations.AddField(
            model_name='assetmapout',
            name='current_asset_bundle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='roommanager.HardwareBundle'),
        ),
    ]
