# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2021-01-13 18:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roommanager', '0086_auto_20210110_2031'),
    ]

    operations = [
        migrations.CreateModel(
            name='SwapTagLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_tag', models.CharField(max_length=50)),
                ('new_tag', models.CharField(max_length=50)),
                ('tech_username', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('approved', models.BooleanField(default=False)),
                ('approved_timestamp', models.DateTimeField()),
            ],
        ),
    ]
