# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2021-01-13 18:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roommanager', '0087_swaptaglog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='swaptaglog',
            name='approved_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
