# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2021-01-26 21:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roommanager', '0088_auto_20210113_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='hardwarebundlepairing',
            name='asset_serial_number',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='machine',
            name='asset_serial_number',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
