# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2021-01-28 19:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roommanager', '0089_auto_20210126_2126'),
    ]

    operations = [
        migrations.AddField(
            model_name='bundlechangeapproval',
            name='reject',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bundlechangeapproval',
            name='rejected_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
