# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2021-01-28 19:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roommanager', '0090_auto_20210128_1950'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bundlechangeapproval',
            old_name='reject',
            new_name='rejected',
        ),
    ]
