# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2021-03-18 21:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('roommanager', '0093_auto_20210210_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='bundlechangeapproval',
            name='decision_maker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
