# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2021-03-31 11:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roommanager', '0094_bundlechangeapproval_decision_maker'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='custom_description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
