# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2021-04-01 14:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roommanager', '0095_slot_custom_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlotView',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('roommanager.slot',),
        ),
    ]
