# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2021-04-19 18:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roommanager', '0097_auto_20210419_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bundlechangeapproval',
            name='change_type',
            field=models.CharField(blank=True, choices=[('SLOT_CHANGE', 'SLOT_CHANGE'), ('MACHINE_CHANGE', 'MACHINE_CHANGE'), ('CARD_READER_CHANGE', 'CARD_READER_CHANGE')], max_length=50, null=True),
        ),
    ]
