# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2021-04-20 20:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roommanager', '0099_auto_20210420_2046'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='equipment_types',
            field=models.ManyToManyField(blank=True, null=True, related_name='machines_m2m', to='roommanager.EquipmentType'),
        ),
    ]
