# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2021-04-23 19:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roommanager', '0100_machine_equipment_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='equipment_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='roommanager.EquipmentType'),
        ),
    ]
