# Generated by Django 3.1 on 2021-05-15 14:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('roommanager', '0101_slot_equipment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetmapout',
            name='assigned_technician',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='roommanager.technicianemployeeprofile'),
        ),
        migrations.AlterField(
            model_name='assetmapout',
            name='current_asset_bundle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='roommanager.hardwarebundle'),
        ),
        migrations.AlterField(
            model_name='bundlechangeapproval',
            name='decision_maker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bundlechangeapproval',
            name='previous_bundle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='roommanager.hardwarebundle'),
        ),
        migrations.AlterField(
            model_name='bundlechangeapproval',
            name='scan_pairing',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='roommanager.hardwarebundlepairing'),
        ),
        migrations.AlterField(
            model_name='equipmenttype',
            name='laundry_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='roommanager.laundrygroup'),
        ),
        migrations.AlterField(
            model_name='equipmenttypeschedule',
            name='equipment_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='roommanager.equipmenttype'),
        ),
        migrations.AlterField(
            model_name='equipmenttypeschedule',
            name='laundry_room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedules', to='roommanager.laundryroom'),
        ),
        migrations.AlterField(
            model_name='hardwarebundlechangeslog',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hardware_bundle_changes', to='roommanager.laundryroom'),
        ),
        migrations.AlterField(
            model_name='hardwarebundlechangeslog',
            name='new_bundle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='new_bundle', to='roommanager.hardwarebundle'),
        ),
        migrations.AlterField(
            model_name='hardwarebundlechangeslog',
            name='old_bundle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='old_bundle', to='roommanager.hardwarebundle'),
        ),
        migrations.AlterField(
            model_name='hardwarebundlechangeslog',
            name='technician',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='roommanager.technicianemployeeprofile'),
        ),
        migrations.AlterField(
            model_name='hardwarebundlerequirement',
            name='assigned_technician',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='roommanager.technicianemployeeprofile'),
        ),
        migrations.AlterField(
            model_name='laundryroom',
            name='laundry_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='roommanager.laundrygroup'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='equipment_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='machine', to='roommanager.equipmenttype'),
        ),
        migrations.AlterField(
            model_name='machineslotmap',
            name='machine',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='roommanager.machine'),
        ),
        migrations.AlterField(
            model_name='machineslotmap',
            name='slot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='roommanager.slot'),
        ),
        migrations.AlterField(
            model_name='orphanedpiecerequiredanswer',
            name='hbr',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='roommanager.hardwarebundlerequirement'),
        ),
        migrations.AlterField(
            model_name='slot',
            name='equipment_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='roommanager.equipmenttype'),
        ),
    ]
