# Generated by Django 3.1.1 on 2021-05-22 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roommanager', '0102_auto_20210515_1410'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='workorderrecord',
            index=models.Index(fields=['asset_upkeep_id'], name='roommanager_asset_u_4119cb_idx'),
        ),
    ]
