# Generated by Django 3.1.1 on 2021-05-27 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roommanager', '0103_auto_20210522_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='hardwarebundlepairing',
            name='dual_pocket_new_bundle',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hardwarebundlepairing',
            name='slot_being_replaced',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='hardwarebundle',
            name='bundle_type',
            field=models.CharField(blank=True, choices=[('STACKDRYER', 'STACKDRYER'), ('STACKDRYER_DUALPOCKET', 'STACKDRYER_DUALPOCKET'), ('SINGLE', 'SINGLE'), ('WAREHOUSE', 'WAREHOUSE')], default='SINGLE', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='hardwarebundlepairing',
            name='scan_type',
            field=models.CharField(blank=True, choices=[('STACKDRYER', 'STACKDRYER'), ('STACKDRYER_DUALPOCKET', 'STACKDRYER_DUALPOCKET'), ('SINGLE', 'SINGLE'), ('WAREHOUSE', 'WAREHOUSE')], max_length=40, null=True),
        ),
    ]
