# Generated by Django 3.1.1 on 2021-06-07 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roommanager', '0105_bundlechangeapproval_superseded_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='technicianemployeeprofile',
            name='language',
            field=models.CharField(choices=[('Spanish', 'Spanish'), ('English', 'English')], default='English', max_length=20),
        ),
    ]
