# Generated by Django 3.1.1 on 2021-06-12 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roommanager', '0106_technicianemployeeprofile_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='asset_factory_model',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
