# Generated by Django 3.1.1 on 2021-06-12 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roommanager', '0107_machine_asset_factory_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='hardwarebundlepairing',
            name='asset_factory_model',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
