# Generated by Django 3.1.1 on 2021-06-17 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roommanager', '0108_hardwarebundlepairing_asset_factory_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='laundryroom',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
