# Generated by Django 3.1.1 on 2021-06-17 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roommanager', '0109_laundryroom_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laundryroom',
            name='creation_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
