# Generated by Django 3.1.1 on 2021-07-04 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('revenue', '0070_auto_20210629_2208'),
        ('roommanager', '0110_auto_20210617_2048'),
    ]

    operations = [
        migrations.AddField(
            model_name='technicianemployeeprofile',
            name='fascard_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='revenue.fascarduser'),
        ),
    ]
