# Generated by Django 3.1.1 on 2021-07-07 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roommanager', '0112_laundryroom_maintainx_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardreaderasset',
            name='maintainx_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
