# Generated by Django 3.1.1 on 2021-07-07 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roommanager', '0113_cardreaderasset_maintainx_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='maintainx_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
