# Generated by Django 3.1.1 on 2021-07-10 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roommanager', '0115_hardwarebundlepairing_file_transfer_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='hardwarebundlepairing',
            name='file_upload_path',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
