# Generated by Django 3.1.1 on 2021-07-11 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roommanager', '0117_auto_20210710_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardreadermeter',
            name='maintainx_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='laundryroommeter',
            name='maintainx_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='machinemeter',
            name='maintainx_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
