# Generated by Django 3.1.1 on 2021-07-14 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roommanager', '0118_auto_20210711_1936'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintainxWorkOrderRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=50, null=True)),
                ('completed_date', models.DateTimeField(blank=True, null=True)),
                ('created_date', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField(blank=True, max_length=2000, null=True)),
                ('status', models.CharField(blank=True, max_length=30, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('updated_date', models.DateTimeField(blank=True, null=True)),
                ('asset_maintainx_id', models.CharField(blank=True, max_length=30, null=True)),
                ('assigned_by_id', models.CharField(blank=True, max_length=30, null=True)),
                ('assignees_ids', models.CharField(blank=True, max_length=30, null=True)),
                ('completed_by_id', models.CharField(blank=True, max_length=30, null=True)),
                ('location_maintainx_id', models.CharField(blank=True, max_length=30, null=True)),
                ('priority_level', models.CharField(blank=True, max_length=50, null=True)),
                ('maintainx_id', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
