# Generated by Django 3.1.1 on 2021-07-18 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roommanager', '0119_maintainxworkorderrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintainxUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintainx_id', models.CharField(blank=True, max_length=20, null=True)),
                ('first_name', models.CharField(blank=True, max_length=20, null=True)),
                ('last_name', models.CharField(blank=True, max_length=20, null=True)),
                ('role', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('removed_from_organization', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='maintainxworkorderrecord',
            name='assignees',
            field=models.ManyToManyField(to='roommanager.MaintainxUser'),
        ),
    ]
