# Generated by Django 3.1.1 on 2021-07-24 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roommanager', '0120_auto_20210718_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='swaptaglog',
            name='tech_username',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
