# Generated by Django 3.1.1 on 2021-10-11 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roommanager', '0122_assetmapout_assigned_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintainxWorkOrderPart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintainx_id', models.CharField(blank=True, max_length=30, null=True)),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('area', models.CharField(blank=True, max_length=30, null=True)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('available_quantity', models.IntegerField(blank=True, null=True)),
                ('barcode', models.CharField(blank=True, max_length=30, null=True)),
                ('copy_on_recurring', models.CharField(blank=True, max_length=30, null=True)),
                ('minimum_quantity', models.CharField(blank=True, max_length=30, null=True)),
                ('quantity_used', models.CharField(blank=True, max_length=30, null=True)),
                ('unit_cost', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='machine',
            name='asset_code',
            field=models.CharField(blank=True, help_text='This field is synced to Upkeep and Fascard', max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='machine',
            name='asset_serial_number',
            field=models.CharField(blank=True, help_text='This field is synced to Upkeep and Fascard', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='machine',
            name='machine_description',
            field=models.CharField(blank=True, help_text='This field is synced to Upkeep', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='maintainxworkorderrecord',
            name='parts',
            field=models.ManyToManyField(to='roommanager.MaintainxWorkOrderPart'),
        ),
    ]
