# Generated by Django 3.1.1 on 2021-12-18 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roommanager', '0123_auto_20211011_2139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintainxworkorderpart',
            name='quantity_used',
        ),
    ]
