# Generated by Django 3.1.1 on 2021-12-19 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roommanager', '0126_auto_20211218_2319'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintainxworkorderrecord',
            name='associated_upkeep_wo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='roommanager.workorderrecord'),
        ),
    ]
