# Generated by Django 3.1.1 on 2021-12-19 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roommanager', '0127_maintainxworkorderrecord_associated_upkeep_wo'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintainxworkorderpart',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='maintainxworkorderrecord',
            name='duedate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workorderrecord',
            name='duedate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
