# Generated by Django 3.1.1 on 2021-12-20 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roommanager', '0128_auto_20211219_2214'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorderrecord',
            name='associated_maintainx_id',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
