# Generated by Django 3.1.1 on 2021-12-21 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roommanager', '0129_workorderrecord_associated_maintainx_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='technicianemployeeprofile',
            name='maintainx_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
