# Generated by Django 3.1.1 on 2021-12-27 15:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('roommanager', '0130_technicianemployeeprofile_maintainx_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetUpdateApproval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved', models.BooleanField(default=False)),
                ('rejected', models.BooleanField(default=False)),
                ('rejected_timestamp', models.DateTimeField(blank=True, null=True)),
                ('approved_timestamp', models.DateTimeField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('decision_maker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('scan_pairing', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='roommanager.hardwarebundlepairing')),
                ('superseded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='roommanager.assetupdateapproval')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
