# Generated by Django 3.1.1 on 2022-01-03 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roommanager', '0131_assetupdateapproval'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetupdateapproval',
            name='bundle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='roommanager.hardwarebundle'),
        ),
    ]
