# Generated by Django 3.1.1 on 2022-02-22 00:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('revenue', '0072_auto_20210827_2208'),
        ('roommanager', '0132_assetupdateapproval_bundle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orphanedpiecerequiredanswer',
            name='answer',
            field=models.CharField(blank=True, choices=[('warehouse', 'Warehouse'), ('office', 'Office'), ('brooklyn', 'Brooklyn Office'), ('other-room', 'Another Laundry Room'), ('other-slot-same-room', 'Another Slot in the same Room'), ('disposed', 'Being Disposed'), ('sold', 'Sold'), ('manufacturer', 'Returning to Manufactureer'), ('abandoned', 'Abandoned on Site'), ('rebundled', 'Will get rebundled with same CardReader/Machine'), ('new-hardware-bundle', 'Get Bundled with new Hardware'), ('deleted', 'Will get Deleted')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='technicianemployeeprofile',
            name='fascard_user',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_employee': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='revenue.fascarduser'),
        ),
    ]
