# Generated by Django 3.1.1 on 2022-02-27 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roommanager', '0133_auto_20220222_0014'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetupdateapproval',
            name='serial_number_not_available',
            field=models.BooleanField(default=False, help_text='Chec if Serial # NOT Available'),
        ),
    ]
