# Generated by Django 3.1.1 on 2022-11-12 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roommanager', '0135_auto_20220227_1924'),
    ]

    operations = [
        migrations.CreateModel(
            name='MachineMeterReading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_reading', models.IntegerField()),
                ('picture', models.ImageField(upload_to='meter_readings')),
                ('approved', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meter_readings', to='roommanager.machine')),
            ],
        ),
    ]
