# Generated by Django 3.1.1 on 2022-11-26 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roommanager', '0137_hardwarebundlepairing_machine_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetupdateapproval',
            name='asset_picture_decision',
            field=models.CharField(blank=True, choices=[('ACCEPT_AND_REPLACE', 'Accept and Replace Current'), ('SAVE_DONT_REPLACE', 'Save Picture But Do Not Replace Current'), ('REJECT', 'Reject')], default=('NA', 'na'), max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='assetupdateapproval',
            name='asset_serial_picture_decision',
            field=models.CharField(blank=True, choices=[('ACCEPT_AND_REPLACE', 'Accept and Replace Current'), ('SAVE_DONT_REPLACE', 'Save Picture But Do Not Replace Current'), ('REJECT', 'Reject')], default=('NA', 'na'), max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='bundlechangeapproval',
            name='asset_picture_decision',
            field=models.CharField(blank=True, choices=[('ACCEPT_AND_REPLACE', 'Accept and Replace Current'), ('SAVE_DONT_REPLACE', 'Save Picture But Do Not Replace Current'), ('REJECT', 'Reject')], default=('NA', 'na'), max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='bundlechangeapproval',
            name='asset_serial_picture_decision',
            field=models.CharField(blank=True, choices=[('ACCEPT_AND_REPLACE', 'Accept and Replace Current'), ('SAVE_DONT_REPLACE', 'Save Picture But Do Not Replace Current'), ('REJECT', 'Reject')], default=('NA', 'na'), max_length=20, null=True),
        ),
    ]
