# Generated by Django 3.1.1 on 2022-12-02 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roommanager', '0139_auto_20221202_2013'),
    ]

    operations = [
        migrations.AddField(
            model_name='hardwarebundlepairing',
            name='asset_picture_decision',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='hardwarebundlepairing',
            name='asset_serial_picture_decision',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
