# Generated by Django 3.1.1 on 2022-12-17 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roommanager', '0142_auto_20221202_2117'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintainxZipCodeRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintainx_id', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('display_name', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='laundryroom',
            name='maintainx_zipcode_location_parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='roommanager.maintainxzipcoderoom'),
        ),
    ]
