# Generated by Django 3.1.1 on 2022-12-21 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roommanager', '0143_auto_20221217_2212'),
    ]

    operations = [
        migrations.AddField(
            model_name='laundryroom',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='laundryroom',
            name='latitude',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='laundryroom',
            name='longitude',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
