# Generated by Django 3.1.1 on 2022-12-21 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roommanager', '0144_auto_20221221_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='laundryroom',
            name='room_zip_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
