# Generated by Django 3.1.1 on 2022-12-23 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roommanager', '0146_machineattachmenttracker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machineattachmenttracker',
            name='attachment_maintainx_url',
            field=models.CharField(max_length=300),
        ),
    ]
