# Generated by Django 3.1.1 on 2023-01-08 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roommanager', '0147_auto_20221223_2315'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetupdateapproval',
            name='machine_description',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bundlechangeapproval',
            name='machine_description',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
