# Generated by Django 3.1.1 on 2023-01-08 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roommanager', '0148_auto_20230108_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetupdateapproval',
            name='machine_description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='bundlechangeapproval',
            name='machine_description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
