# Generated by Django 3.1.1 on 2023-05-08 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roommanager', '0150_laundryroom_test_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='technicianemployeeprofile',
            name='maintainx_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='roommanager.maintainxuser'),
        ),
    ]
