# Generated by Django 3.1.1 on 2023-05-11 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roommanager', '0151_technicianemployeeprofile_maintainx_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetupdateapproval',
            name='associated_work_order_maintainx_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='bundlechangeapproval',
            name='associated_work_order_maintainx_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
