# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-05 18:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('roommanager', '0002_auto_20170305_1727'),
    ]

    operations = [
        migrations.CreateModel(
            name='FascardUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=1000, null=True)),
                ('addr_1', models.CharField(blank=True, max_length=1000, null=True)),
                ('addr_2', models.CharField(blank=True, max_length=1000, null=True)),
                ('city', models.CharField(blank=True, max_length=200, null=True)),
                ('state', models.CharField(blank=True, max_length=200, null=True)),
                ('zip', models.CharField(blank=True, max_length=200, null=True)),
                ('mobile_phone', models.CharField(blank=True, max_length=200, null=True)),
                ('office_phone', models.CharField(blank=True, max_length=200, null=True)),
                ('email_address', models.CharField(blank=True, max_length=1000, null=True)),
                ('comments', models.CharField(blank=True, max_length=1000, null=True)),
                ('language', models.CharField(blank=True, max_length=200, null=True)),
                ('notify_cycle_complete', models.CharField(blank=True, max_length=200, null=True)),
                ('fascard_creation_date', models.DateTimeField(blank=True, null=True)),
                ('fascard_last_activity_date', models.DateTimeField(blank=True, null=True)),
                ('balance', models.FloatField(blank=True, null=True)),
                ('bonus', models.FloatField(blank=True, null=True)),
                ('discount', models.FloatField(blank=True, null=True)),
                ('free_starts', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=200, null=True)),
                ('is_employee', models.NullBooleanField()),
                ('loyalty_points', models.FloatField(blank=True, null=True)),
                ('ballance_spent', models.FloatField(blank=True, null=True)),
                ('bonus_spent', models.FloatField(blank=True, null=True)),
                ('free_starts_spent', models.FloatField(blank=True, null=True)),
                ('reload_method', models.FloatField(blank=True, null=True)),
                ('reload_balance', models.FloatField(blank=True, null=True)),
                ('reload_bonus', models.FloatField(blank=True, null=True)),
                ('cash_spent', models.FloatField(blank=True, null=True)),
                ('credit_card_spent', models.FloatField(blank=True, null=True)),
                ('user_group_id', models.IntegerField(blank=True, null=True)),
                ('last_location_id', models.IntegerField(blank=True, null=True)),
                ('xxx_caution_fascard_user_id', models.IntegerField(blank=True, null=True)),
                ('fascard_user_account_id', models.IntegerField()),
                ('coupons', models.CharField(blank=True, max_length=200, null=True)),
                ('laundry_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roommanager.LaundryGroup')),
            ],
            options={
                'db_table': 'fascard_user',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='LaundryTransaction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('external_fascard_id', models.CharField(max_length=10, unique=True)),
                ('web_display_name', models.CharField(blank=True, max_length=100, null=True)),
                ('first_name', models.CharField(max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100, null=True)),
                ('local_transaction_date', models.DateField(blank=True, null=True)),
                ('transaction_type', models.CharField(blank=True, max_length=100)),
                ('credit_card_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cash_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ballance_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('last_four', models.CharField(blank=True, max_length=4, null=True)),
                ('utc_transaction_time', models.DateTimeField(blank=True, null=True)),
                ('local_transaction_time', models.DateTimeField(blank=True, null=True)),
                ('external_fascard_user_id', models.IntegerField(blank=True, null=True)),
                ('fascard_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='revenue.FascardUser')),
                ('laundry_room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='roommanager.LaundryRoom')),
                ('machine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='roommanager.Machine')),
                ('slot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='roommanager.Slot')),
            ],
            options={
                'db_table': 'laundry_transaction',
                'managed': True,
            },
        ),
    ]
