# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-06 18:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revenue', '0002_auto_20170305_1856'),
    ]

    operations = [
        migrations.AddField(
            model_name='laundrytransaction',
            name='fascard_code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
