# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-06 18:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revenue', '0003_laundrytransaction_fascard_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='laundrytransaction',
            name='dirty_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
