# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-13 16:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revenue', '0004_laundrytransaction_dirty_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='laundrytransaction',
            name='utc_transaction_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
