# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-24 07:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('revenue', '0005_laundrytransaction_is_refunded'),
        ('revenue', '0005_laundrytransaction_utc_transaction_date'),
    ]

    operations = [
    ]
