# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-05-10 18:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revenue', '0005_laundrytransaction_utc_transaction_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='laundrytransaction',
            name='authorizedotnet_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='laundrytransaction',
            name='loyalty_card_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
