# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-05-21 15:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revenue', '0006_auto_20170510_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='laundrytransaction',
            name='card_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
