# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-05-30 07:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('revenue', '0006_merge_20170424_0702'),
        ('revenue', '0006_auto_20170510_1832'),
    ]

    operations = [
    ]
