# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-05-22 19:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revenue', '0007_laundrytransaction_card_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='FailedLaundryTransactionIngest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('external_fascard_id', models.CharField(blank=True, max_length=255, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('row', models.TextField()),
                ('error_message', models.TextField(blank=True, null=True)),
                ('resolved', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'failed_laundry_transaction_ingest',
                'managed': True,
            },
        ),
    ]
