# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-06-01 01:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revenue', '0008_auto_20170530_0813'),
    ]

    operations = [
        migrations.AddField(
            model_name='refund',
            name='card_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
