# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-07-07 15:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revenue', '0008_failedlaundrytransactioningest'),
    ]

    operations = [
        migrations.AddField(
            model_name='laundrytransaction',
            name='additional_info',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='laundrytransaction',
            name='bonus_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='laundrytransaction',
            name='card_type',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='laundrytransaction',
            name='employee_user_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='laundrytransaction',
            name='free_starts',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='laundrytransaction',
            name='loyalty_points',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='laundrytransaction',
            name='new_balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='laundrytransaction',
            name='new_bonus',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='laundrytransaction',
            name='new_free_starts',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='laundrytransaction',
            name='new_loyalty_points',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='laundrytransaction',
            name='root_transaction_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='laundrytransaction',
            name='sys_config_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='laundrytransaction',
            name='trans_sub_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='laundrytransaction',
            name='unfunded_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
