# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-02-06 20:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roommanager', '0004_auto_20170609_1744'),
        ('revenue', '0009_auto_20170707_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='laundrytransaction',
            name='assigned_laundry_room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_room', to='roommanager.LaundryRoom'),
        ),
        migrations.AddField(
            model_name='laundrytransaction',
            name='assigned_local_transaction_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='laundrytransaction',
            name='assigned_utc_transaction_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
