# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-02-18 16:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('revenue', '0010_auto_20180206_2025'),
        ('revenue', '0009_refund_card_number'),
    ]

    operations = [
    ]
