# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-03-03 00:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revenue', '0011_merge_20180218_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refund',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
