# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-10-17 14:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('revenue', '0013_auto_20180617_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laundrytransaction',
            name='fascard_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='revenue.FascardUser'),
        ),
        migrations.AlterField(
            model_name='refund',
            name='refund_type',
            field=models.CharField(choices=[('Fascard', 'Fascard'), ('AuthorizeDotNet', 'AuthorizeDotNet')], max_length=255),
        ),
    ]
