# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-10-02 17:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revenue', '0013_auto_20180617_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refund',
            name='refund_type',
            field=models.CharField(choices=[('Fascard', 'Fascard'), ('AuthorizeDotNet', 'AuthorizeDotNet')], max_length=255),
        ),
    ]
