# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-11-21 17:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('revenue', '0014_auto_20191017_1459'),
    ]

    operations = [
        migrations.CreateModel(
            name='FailedTransactionMatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('solved', models.BooleanField(default=False)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='revenue.LaundryTransaction')),
            ],
        ),
    ]
