# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-11-28 09:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('revenue', '0014_auto_20191002_1704'),
        ('revenue', '0015_failedtransactionmatch'),
    ]

    operations = [
    ]
