# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-02-07 18:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('revenue', '0016_merge_20191128_0933'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckAttributionMatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_fascard_id', models.CharField(max_length=65, unique=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='revenue.FascardUser')),
            ],
        ),
        migrations.AddField(
            model_name='failedtransactionmatch',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
