# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-02-22 13:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revenue', '0018_auto_20200210_1719'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionGaps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_ids', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('finished', models.BooleanField(default=False)),
            ],
        ),
    ]
