# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-02-22 13:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revenue', '0019_transactiongaps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactiongaps',
            name='transaction_ids',
            field=models.TextField(max_length=1000),
        ),
    ]
