# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-02-26 22:27
from __future__ import unicode_literals

from django.db import migrations, models
import storages.backends.s3boto3


class Migration(migrations.Migration):

    dependencies = [
        ('revenue', '0021_auto_20200222_1336'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionsPool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ids_file', models.FileField(blank=True, null=True, storage=storages.backends.s3boto3.S3Boto3Storage(bucket='transaction-ids-pool'), upload_to='')),
                ('number_of_records', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('fully_processed', models.BooleanField(default=False)),
            ],
        ),
    ]
