# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-02-26 23:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revenue', '0023_auto_20200226_2323'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactiongaps',
            name='number_of_records',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
