# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-03-28 09:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revenue', '0024_transactiongaps_number_of_records'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionspool',
            name='processed_transactions_counter',
            field=models.IntegerField(default=0),
        ),
    ]
