# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-08-19 07:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('revenue', '0025_transactionspool_processed_transactions_counter'),
    ]

    operations = [
        migrations.AddField(
            model_name='refund',
            name='fascard_user_account_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='laundrytransaction',
            name='machine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='roommanager.Machine'),
        ),
        migrations.AlterField(
            model_name='refund',
            name='refund_type',
            field=models.CharField(choices=[(0, 0), (1, 1), (2, 2)], max_length=255),
        ),
    ]
