# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-08-20 09:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('revenue', '0026_auto_20200819_0724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laundrytransaction',
            name='refund',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='revenue.Refund'),
        ),
        migrations.AlterField(
            model_name='refund',
            name='refund_type',
            field=models.CharField(choices=[(0, 'Authorize.net CC Refund'), (1, 'Fascard Balance Adjust'), (2, 'Check')], max_length=255),
        ),
    ]
