# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-08-20 09:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('revenue', '0027_auto_20200820_0952'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='refund',
            name='card_number',
        ),
    ]
