# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-08-24 13:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('revenue', '0028_remove_refund_card_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='RefundAuthorizationRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authorized', models.BooleanField()),
                ('approval_time', models.DateTimeField()),
                ('aggregator_param', models.CharField(blank=True, max_length=20, null=True)),
                ('external_fascard_user_id', models.IntegerField()),
                ('refund_type', models.CharField(choices=[(0, 'Authorize.net CC Refund'), (1, 'Fascard Balance Adjust'), (2, 'Check')], max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('authorized_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('transactions', models.ManyToManyField(to='revenue.LaundryTransaction')),
            ],
        ),
    ]
