# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-08-24 14:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revenue', '0029_refundauthorizationrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refundauthorizationrequest',
            name='authorized',
            field=models.BooleanField(default=False),
        ),
    ]
