# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-08-24 14:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('revenue', '0031_auto_20200824_1404'),
    ]

    operations = [
        migrations.RenameField(
            model_name='refundauthorizationrequest',
            old_name='authorized',
            new_name='approved',
        ),
        migrations.RenameField(
            model_name='refundauthorizationrequest',
            old_name='authorized_by',
            new_name='approved_by',
        ),
    ]
