# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-08-24 15:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revenue', '0033_refundauthorizationrequest_refund_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refundauthorizationrequest',
            name='refund_type',
            field=models.IntegerField(choices=[(0, 'Authorize.net CC Refund'), (1, 'Fascard Balance Adjust'), (2, 'Check')], max_length=255),
        ),
    ]
