# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-08-25 08:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revenue', '0034_auto_20200824_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refundauthorizationrequest',
            name='refund_type',
            field=models.CharField(choices=[(0, 'Authorize.net CC Refund'), (1, 'Fascard Balance Adjust'), (2, 'Check')], max_length=255),
        ),
    ]
