# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-08-25 08:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revenue', '0035_auto_20200825_0801'),
    ]

    operations = [
        migrations.AddField(
            model_name='refundauthorizationrequest',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='refundauthorizationrequest',
            name='refund_type',
            field=models.IntegerField(choices=[(0, 'Authorize.net CC Refund'), (1, 'Fascard Balance Adjust'), (2, 'Check')], max_length=255),
        ),
    ]
