# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-08-25 08:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('revenue', '0037_auto_20200825_0841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laundrytransaction',
            name='refund',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='revenue.Refund'),
        ),
    ]
