# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-08-25 15:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revenue', '0039_refundauthorizationrequest_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refund',
            name='refund_type',
            field=models.IntegerField(choices=[(0, 'Authorize.net CC Refund'), (1, 'Fascard Balance Adjust'), (2, 'Check')], max_length=255),
        ),
    ]
