# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-08-28 11:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revenue', '0040_auto_20200825_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='refundauthorizationrequest',
            name='wait_for_settlement',
            field=models.BooleanField(default=False),
        ),
    ]
