# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-10-09 21:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revenue', '0045_refundauthorizationrequest_custom_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='refundauthorizationrequest',
            name='work_order_status',
            field=models.CharField(blank=True, choices=[('Complete', 'Complete'), ('On Hold', 'On Hold'), ('Open', 'Open'), ('In Progress', 'In Progress')], max_length=30, null=True),
        ),
    ]
