# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-12-22 19:58
from __future__ import unicode_literals

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revenue', '0048_auto_20201222_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refundauthorizationrequest',
            name='additional_bonus_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True, validators=[django.core.validators.MaxValueValidator(Decimal('100.00')), django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
