# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2021-01-12 16:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revenue', '0049_auto_20201222_1958'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='laundrytransaction',
            index=models.Index(fields=['local_transaction_date'], name='laundry_tra_local_t_7491a4_idx'),
        ),
    ]
