# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2021-01-18 17:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('revenue', '0051_auto_20210118_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='refundauthorizationrequest',
            name='fascard_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='revenue.FascardUser'),
        ),
    ]
