# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2021-01-22 18:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import storages.backends.s3boto3


class Migration(migrations.Migration):

    dependencies = [
        ('revenue', '0052_refundauthorizationrequest_fascard_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='RefundFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refund_file', models.FileField(blank=True, null=True, storage=storages.backends.s3boto3.S3Boto3Storage(bucket='refunds-files'), upload_to='')),
                ('refund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='revenue.Refund')),
            ],
        ),
    ]
