# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2021-01-22 19:10
from __future__ import unicode_literals

from django.db import migrations, models
import storages.backends.s3boto3


class Migration(migrations.Migration):

    dependencies = [
        ('revenue', '0053_refundfile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='refundfile',
            name='refund',
        ),
        migrations.AddField(
            model_name='refund',
            name='refund_file',
            field=models.FileField(blank=True, null=True, storage=storages.backends.s3boto3.S3Boto3Storage(bucket='refunds-files'), upload_to=''),
        ),
        migrations.DeleteModel(
            name='RefundFile',
        ),
    ]
