# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2021-02-06 18:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revenue', '0054_auto_20210122_1910'),
    ]

    operations = [
        migrations.AddField(
            model_name='refundauthorizationrequest',
            name='rejected',
            field=models.BooleanField(default=False),
        ),
    ]
