# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2021-02-27 21:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('revenue', '0055_refundauthorizationrequest_rejected'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorizeCustomerProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loyalty_card_number', models.CharField(max_length=50)),
                ('authorize_customer_id', models.CharField(max_length=50)),
                ('fascard_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='revenue.FascardUser')),
            ],
        ),
        migrations.CreateModel(
            name='eCheckSubscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance_minimum_treshold', models.DecimalField(decimal_places=2, max_digits=6)),
                ('balance_recharge', models.DecimalField(decimal_places=2, max_digits=6)),
                ('confirmed', models.BooleanField(default=False)),
                ('customer_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='revenue.AuthorizeCustomerProfile')),
            ],
        ),
    ]
