# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2021-02-28 09:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revenue', '0056_authorizecustomerprofile_echecksubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorizecustomerprofile',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
