# Generated by Django 3.1 on 2021-05-15 14:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roommanager', '0102_auto_20210515_1410'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('revenue', '0058_txlastidlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='failedtransactionmatch',
            name='transaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='revenue.laundrytransaction'),
        ),
        migrations.AlterField(
            model_name='fascarduser',
            name='laundry_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='roommanager.laundrygroup'),
        ),
        migrations.AlterField(
            model_name='laundrytransaction',
            name='assigned_laundry_room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_room', to='roommanager.laundryroom'),
        ),
        migrations.AlterField(
            model_name='laundrytransaction',
            name='laundry_room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='roommanager.laundryroom'),
        ),
        migrations.AlterField(
            model_name='laundrytransaction',
            name='slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='roommanager.slot'),
        ),
        migrations.AlterField(
            model_name='refund',
            name='authorization_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='revenue.refundauthorizationrequest'),
        ),
        migrations.AlterField(
            model_name='refund',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refunds', to='revenue.laundrytransaction'),
        ),
        migrations.AlterField(
            model_name='refund',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='refundauthorizationrequest',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='refundauthorizationrequest',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='refundauthorizationrequest',
            name='fascard_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='revenue.fascarduser'),
        ),
        migrations.AlterField(
            model_name='refundauthorizationrequest',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='revenue.laundrytransaction'),
        ),
    ]
