# Generated by Django 3.1.1 on 2021-06-01 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('revenue', '0060_refundauthorizationrequest_refunded'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='refundauthorizationrequest',
            name='refunded',
        ),
        migrations.AddField(
            model_name='refund',
            name='refund_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='refund',
            name='authorization_request',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refund_object', to='revenue.refundauthorizationrequest'),
        ),
    ]
