# Generated by Django 3.1.1 on 2021-06-19 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('revenue', '0061_auto_20210601_1416'),
    ]

    operations = [
        migrations.CreateModel(
            name='FakeTx',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('revenue.laundrytransaction',),
        ),
    ]
