# Generated by Django 3.1.1 on 2021-06-23 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revenue', '0067_refundauthorizationrequest_charge_damage_to_landlord'),
    ]

    operations = [
        migrations.RenameField(
            model_name='refund',
            old_name='refund_type',
            new_name='refund_channel',
        ),
        migrations.RenameField(
            model_name='refundauthorizationrequest',
            old_name='refund_type',
            new_name='refund_channel',
        ),
        migrations.AddField(
            model_name='refund',
            name='refund_type_choice',
            field=models.CharField(choices=[('Transaction', 'Transaction'), ('Cashout', 'Cashout'), ('Damage', 'Damage')], default='Transaction', max_length=255),
        ),
    ]
