# Generated by Django 3.1.1 on 2021-06-23 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revenue', '0068_auto_20210623_2108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='refund',
            name='refund_type_choice',
        ),
        migrations.AddField(
            model_name='refundauthorizationrequest',
            name='refund_type_choice',
            field=models.CharField(choices=[('Transaction', 'Transaction'), ('Cashout', 'Cashout'), ('Damage', 'Damage')], default='Transaction', max_length=255),
        ),
    ]
