# Generated by Django 3.1.1 on 2021-06-29 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revenue', '0069_auto_20210623_2236'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='laundrytransaction',
            name='laundry_tra_local_t_ea75b0_idx',
        ),
        migrations.AddField(
            model_name='refundauthorizationrequest',
            name='force_charge_landlord_choice',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='laundrytransaction',
            index=models.Index(fields=['local_transaction_date', 'local_transaction_time', 'fascard_record_id'], name='laundry_tra_local_t_00dd80_idx'),
        ),
    ]
