# Generated by Django 3.1.1 on 2021-07-28 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revenue', '0070_auto_20210629_2208'),
    ]

    operations = [
        migrations.AddField(
            model_name='refundauthorizationrequest',
            name='check_recipient_address',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
