# Generated by Django 3.1.1 on 2021-08-27 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revenue', '0071_refundauthorizationrequest_check_recipient_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refundauthorizationrequest',
            name='aggregator_param',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
