# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-13 08:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('roommanager', '0002_auto_20170305_1727'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingGroup',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('display_name', models.CharField(max_length=200, unique=True)),
                ('revenue_split_level', models.CharField(choices=[(b'ROOM', b'Room'), (b'BILLING_GROUP', b'Billing Group')], max_length=1000)),
                ('schedule_type', models.CharField(choices=[(b'CONSTANT', b'Constant'), (b'GROSS_REVENUE', b'Gross Revenue'), (b'TIME', b'Time- NOT YET IMPLEMENTED')], max_length=1000)),
                ('min_compensation_per_day', models.FloatField(blank=True, null=True)),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='LaundryRoomExtension',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('num_units', models.IntegerField(blank=True, null=True)),
                ('square_feet_residential', models.IntegerField(blank=True, null=True)),
                ('has_elevator', models.NullBooleanField()),
                ('is_outdoors', models.NullBooleanField()),
                ('billing_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reporting.BillingGroup')),
                ('laundry_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roommanager.LaundryRoom', unique=True)),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MetricsCache',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('metric_type', models.CharField(blank=True, choices=[(b'REVENUE FUNDS', b'REVENUE FUNDS'), (b'REVENUE EARNED', b'REVENUE EARNED'), (b'REVENUE CREDIT CARD AT MACHINE', b'REVENUE CREDIT CARD AT MACHINE'), (b'REVENUE ADD VALUE VIA CREDIT CARD', b'REVENUE ADD VALUE VIA CREDIT CARD'), (b'REVENUE ADD VALUE VIA CASH', b'REVENUE ADD VALUE VIA CASH'), (b'REVENUE FUNDS CREDIT', b'REVENUE FUNDS CREDIT'), (b'REVENUE FUNDS CASH', b'REVENUE FUNDS CASH')], max_length=255, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('duration', models.CharField(blank=True, choices=[(b'DAY', b'DAY'), (b'MONTH', b'MONTH'), (b'YEAR', b'YEAR')], max_length=255, null=True)),
                ('location_level', models.CharField(blank=True, choices=[(b'LAUNDRY ROOM', b'LAUNDRY ROOM'), (b'MACHINE', b'MACHINE')], max_length=255, null=True)),
                ('result', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
            ],
            options={
                'db_table': 'metrics_cache',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='RevenueSplitRule',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('revenue_split_formula', models.CharField(choices=[(b'PERCENT', b'Percent'), (b'NATURAL_BREAKPOINT', b'Natural Breakpoint'), (b'GENERAL_BREAKPOINT', b'General Breakpoint')], max_length=1000)),
                ('min_payment', models.FloatField(blank=True, null=True, verbose_name=b'Base rent')),
                ('landloard_split_percent', models.FloatField(blank=True, null=True, verbose_name=b'Landlord revenue split proportion')),
                ('split_threshold', models.FloatField(blank=True, null=True, verbose_name=b'Breakpoint | on revenue split deals')),
                ('start_gross_revenue', models.IntegerField(blank=True, null=True, verbose_name=b'Gross Revenue | rule split effectuation amount')),
                ('end_gross_revenue', models.IntegerField(blank=True, null=True, verbose_name=b'Gross Revenue | rule split termination amount')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name=b'Date | rule split effectuation date')),
                ('final_date', models.DateField(blank=True, null=True, verbose_name=b'Date | rule split termination date')),
                ('billing_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reporting.BillingGroup')),
                ('laundry_room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='roommanager.LaundryRoom')),
            ],
            options={
                'db_table': 'revenue_split_rule',
                'managed': True,
            },
        ),
    ]
