# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-12 14:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='metricscache',
            unique_together=set([('metric_type', 'start_date', 'duration', 'location_level')]),
        ),
    ]
