# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-14 00:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0005_auto_20170414_0033'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='billinggroup',
            table='billing_group',
        ),
        migrations.AlterModelTable(
            name='laundryroomextension',
            table='laundry_room_extension',
        ),
    ]
