# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-14 02:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0006_auto_20170414_0035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laundryroomextension',
            name='billing_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reporting.BillingGroup'),
        ),
    ]
