# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-14 02:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0007_auto_20170414_0208'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='billinggroupexpensetypemap',
            table='billing_group_expense_expense_type_map',
        ),
    ]
