# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-14 14:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0009_auto_20170414_0219'),
    ]

    operations = [
        migrations.RenameField(
            model_name='revenuesplitrule',
            old_name='min_payment',
            new_name='base_rent',
        ),
    ]
