# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-14 14:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0010_auto_20170414_1439'),
    ]

    operations = [
        migrations.RenameField(
            model_name='revenuesplitrule',
            old_name='split_threshold',
            new_name='breakpoint',
        ),
    ]
