# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-16 12:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0011_auto_20170414_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='metricscache',
            name='location_id',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='metricscache',
            name='duration',
            field=models.CharField(blank=True, choices=[(b'DAY', b'DAY'), (b'MONTH', b'MONTH'), (b'YEAR', b'YEAR'), (b'BEFORE', b'BEFORE')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='metricscache',
            name='location_level',
            field=models.CharField(blank=True, choices=[(b'LAUNDRY ROOM', b'LAUNDRY ROOM'), (b'MACHINE', b'MACHINE'), (b'BILLING GROUP', b'BILLING GROUP')], max_length=255, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='metricscache',
            unique_together=set([('metric_type', 'start_date', 'duration', 'location_level', 'location_id')]),
        ),
    ]
