# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-18 02:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0012_auto_20170416_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billinggroupexpensetypemap',
            name='billing_group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='reporting.BillingGroup'),
            preserve_default=False,
        ),
    ]
