# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-21 15:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0013_auto_20170418_0248'),
    ]

    operations = [
        migrations.AddField(
            model_name='billinggroup',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
