# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-21 19:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0015_auto_20170421_1857'),
    ]

    operations = [
        migrations.RenameField(
            model_name='laundryroomextension',
            old_name='laundry_in_bulding',
            new_name='laundry_in_unit',
        ),
        migrations.RenameField(
            model_name='laundryroomextension',
            old_name='ownership_type',
            new_name='legal_structure',
        ),
    ]
