# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-06-09 17:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0016_auto_20170421_1917'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='billinggroup',
            options={'managed': True, 'ordering': ['display_name']},
        ),
        migrations.AlterModelOptions(
            name='billinggroupexpensetypemap',
            options={'managed': True, 'ordering': ['billing_group__display_name']},
        ),
        migrations.AlterModelOptions(
            name='expensetype',
            options={'managed': True, 'ordering': ['display_name']},
        ),
        migrations.AlterModelOptions(
            name='laundryroomextension',
            options={'managed': True, 'ordering': ['laundry_room__display_name']},
        ),
        migrations.AlterModelOptions(
            name='revenuesplitrule',
            options={'managed': True, 'ordering': ['billing_group__display_name']},
        ),
    ]
