# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-11-04 14:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0017_auto_20170609_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metricscache',
            name='metric_type',
            field=models.CharField(blank=True, choices=[(b'REVENUE FUNDS', b'REVENUE FUNDS'), (b'REVENUE EARNED', b'REVENUE EARNED'), (b'REVENUE CREDIT CARD AT MACHINE', b'REVENUE CREDIT CARD AT MACHINE'), (b'REVENUE ADD VALUE VIA CREDIT CARD', b'REVENUE ADD VALUE VIA CREDIT CARD'), (b'REVENUE ADD VALUE VIA CASH', b'REVENUE ADD VALUE VIA CASH'), (b'REVENUE FUNDS CREDIT', b'REVENUE FUNDS CREDIT'), (b'REVENUE FUNDS CASH', b'REVENUE FUNDS CASH'), (b'REVENUE NUM NO DATA DAYS', b'REVENUE NUM NO DATA DAYS'), (b'REVENUE NUM ZERO DOLLAR TRANSACTIONS', b'REVENUE NUM ZERO DOLLAR TRANSACTIONS')], max_length=255, null=True),
        ),
    ]
