# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-12-20 19:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roommanager', '0004_auto_20170609_1744'),
        ('reporting', '0018_auto_20171104_1458'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('price_date', models.DateField()),
                ('machine_type', models.CharField(max_length=255)),
                ('cycle_type', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=3, max_digits=10)),
                ('laundry_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roommanager.LaundryRoom')),
            ],
            options={
                'db_table': 'price_history',
                'managed': True,
            },
        ),
        migrations.AlterUniqueTogether(
            name='pricehistory',
            unique_together=set([('laundry_room', 'price_date', 'machine_type', 'cycle_type')]),
        ),
    ]
