# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-05-17 18:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0020_auto_20180303_0000'),
    ]

    operations = [
        migrations.AddField(
            model_name='billinggroup',
            name='aces_collects_cash',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='metricscache',
            name='metric_type',
            field=models.CharField(blank=True, choices=[(b'REVENUE FUNDS', b'REVENUE FUNDS'), (b'REVENUE_FUNDS_CREDIT', b'REVENUE_FUNDS_CREDIT'), (b'REVENUE_FUNDS_CREDIT_PRESENT_ADD_VALUE', b'REVENUE_FUNDS_CREDIT_PRESENT_ADD_VALUE'), (b'REVENUE_FUNDS_CREDIT_WEB_ADD_VALUE', b'REVENUE_FUNDS_CREDIT_WEB_ADD_VALUE'), (b'REVENUE_FUNDS_CREDIT_DIRECT_VEND', b'REVENUE_FUNDS_CREDIT_DIRECT_VEND'), (b'REVENUE_FUNDS_CASH', b'REVENUE_FUNDS_CASH'), (b'REVENUE_FUNDS_CHECK', b'REVENUE_FUNDS_CHECK'), (b'REVENUE_EARNED', b'REVENUE_EARNED'), (b'FASCARD_REVENUE_FUNDS', b'FASCARD_REVENUE_FUNDS'), (b'REVENUE_NUM_ZERO_DOLLAR_TRANSACTIONS', b'REVENUE_NUM_ZERO_DOLLAR_TRANSACTIONS'), (b'REVENUE_NUM_NO_DATA_DAYS', b'REVENUE_NUM_NO_DATA_DAYS')], max_length=255, null=True),
        ),
    ]
