# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-06-17 14:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0021_auto_20180517_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billinggroup',
            name='aces_collects_cash',
            field=models.BooleanField(default=False),
        ),
    ]
