# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2019-06-13 18:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roommanager', '0005_auto_20180428_1658'),
        ('reporting', '0022_auto_20180617_1412'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomPriceHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detection_date', models.DateField()),
                ('cycle_type', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=3, max_digits=10)),
                ('equipment_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roommanager.EquipmentType')),
                ('laundry_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roommanager.LaundryRoom')),
            ],
        ),
    ]
