# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2019-06-15 13:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0023_custompricehistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custompricehistory',
            name='detection_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='custompricehistory',
            name='price',
            field=models.IntegerField(),
        ),
    ]
