# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2019-06-17 15:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0024_auto_20190615_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custompricehistory',
            name='detection_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='custompricehistory',
            name='laundry_room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_history', to='roommanager.LaundryRoom'),
        ),
    ]
