# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2019-06-18 15:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roommanager', '0005_auto_20180428_1658'),
        ('reporting', '0025_auto_20190617_1512'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingPeriod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('equipment_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roommanager.EquipmentType')),
                ('laundry_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_periods', to='roommanager.LaundryRoom')),
            ],
        ),
    ]
