# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2019-06-18 16:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0026_pricingperiod'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricingperiod',
            name='equipment_type',
        ),
    ]
