# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2019-07-08 11:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roommanager', '0006_auto_20190708_1122'),
        ('reporting', '0027_remove_pricingperiod_equipment_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingReportJobInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periods', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('laundry_rooms', models.ManyToManyField(to='roommanager.LaundryRoom')),
            ],
        ),
    ]
