# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2019-07-16 12:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0028_pricingreportjobinfo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pricingreportjobinfo',
            old_name='periods',
            new_name='rolling_mean_periods',
        ),
    ]
