# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2019-07-18 14:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0029_auto_20190716_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricingreportjobinfo',
            name='user_requested_email',
            field=models.EmailField(default='juaneljach10@gmail.com', max_length=254),
            preserve_default=False,
        ),
    ]
