# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2019-08-02 17:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0030_pricingreportjobinfo_user_requested_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientRevenueFullReportJobInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('user_requested_email', models.EmailField(max_length=254)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('billing_groups', models.ManyToManyField(to='reporting.BillingGroup')),
            ],
        ),
    ]
