# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2019-08-06 15:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0031_clientrevenuefullreportjobinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientRevenueJobsTracker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobs_proccesed', models.IntegerField()),
                ('full_report_delivered', models.BooleanField(default=False)),
                ('user_requested_email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.RemoveField(
            model_name='clientrevenuefullreportjobinfo',
            name='user_requested_email',
        ),
        migrations.AddField(
            model_name='clientrevenuefullreportjobinfo',
            name='generated_file',
            field=models.FileField(blank=True, null=True, upload_to=b''),
        ),
        migrations.AddField(
            model_name='clientrevenuefullreportjobinfo',
            name='job_tracker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs_being_tracked', to='reporting.ClientRevenueJobsTracker'),
        ),
    ]
