# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2019-08-06 15:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0032_auto_20190806_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientrevenuejobstracker',
            name='jobs_proccesed',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
