# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2019-08-06 18:29
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0035_auto_20190806_1649'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientReportStoredFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_file', models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location=b'/home/eljach/apps/laundry_system/tmp'), upload_to=b'')),
                ('job_tracker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_files', to='reporting.ClientRevenueJobsTracker')),
                ('laundry_room_extension', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reporting.LaundryRoomExtension')),
            ],
        ),
        migrations.RemoveField(
            model_name='clientrevenuefullreportjobinfo',
            name='generated_file',
        ),
    ]
