# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2019-08-06 22:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0036_auto_20190806_1829'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientreportstoredfile',
            old_name='job_tracker',
            new_name='jobs_tracker',
        ),
    ]
