# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2019-08-07 08:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0037_auto_20190806_2244'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientrevenuefullreportjobinfo',
            old_name='billing_groups',
            new_name='billing_group',
        ),
    ]
