# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-07 19:00
from __future__ import unicode_literals

from django.db import migrations, models
import storages.backends.s3boto3


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0038_auto_20190807_0822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientreportstoredfile',
            name='report_file',
            field=models.FileField(blank=True, null=True, storage=storages.backends.s3boto3.S3Boto3Storage(bucket=b'tmp-revenue-report-files'), upload_to=b''),
        ),
    ]
