# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-28 16:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import storages.backends.s3boto3


class Migration(migrations.Migration):

    dependencies = [
        ('roommanager', '0010_equipmenttype_equipment_start_check_method'),
        ('reporting', '0039_auto_20190807_1900'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingReportJobsTracker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobs_processed', models.IntegerField(blank=True, default=0, null=True)),
                ('full_report_delivered', models.BooleanField(default=False)),
                ('user_requested_email', models.EmailField(max_length=254)),
                ('full_report_file', models.FileField(blank=True, null=True, storage=storages.backends.s3boto3.S3Boto3Storage(bucket=b'tmp-revenue-report-files'), upload_to=b'')),
            ],
        ),
        migrations.RemoveField(
            model_name='pricingreportjobinfo',
            name='laundry_rooms',
        ),
        migrations.RemoveField(
            model_name='pricingreportjobinfo',
            name='user_requested_email',
        ),
        migrations.AddField(
            model_name='pricingreportjobinfo',
            name='laundry_room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pricing_reports', to='roommanager.LaundryRoom'),
        ),
        migrations.AddField(
            model_name='pricingreportjobinfo',
            name='report_pickle_file',
            field=models.FileField(blank=True, null=True, storage=storages.backends.s3boto3.S3Boto3Storage(bucket=b'pricing-changes-pickles'), upload_to=b''),
        ),
    ]
