# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-28 16:53
from __future__ import unicode_literals

from django.db import migrations, models
import storages.backends.s3boto3


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0040_auto_20190828_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricingreportjobstracker',
            name='full_report_file',
            field=models.FileField(blank=True, null=True, storage=storages.backends.s3boto3.S3Boto3Storage(bucket=b'pricing-change-reports'), upload_to=b''),
        ),
    ]
