# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-28 17:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0041_auto_20190828_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricingreportjobinfo',
            name='job_tracker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs_being_tracked', to='reporting.PricingReportJobsTracker'),
        ),
    ]
