# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-11-02 14:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0044_auto_20191030_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='address1',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='laundryroomextension',
            name='building_type',
            field=models.CharField(choices=[('APARTMENTS', 'APARTMENTS'), ('APARTMENT BUILDING', 'APARTMENT BUILDING'), ('DORMITORY', 'DORMITORY'), ('GARDEN APARTMENTS', 'GARDEN APARTMENTS'), ('STUDENT HOUSING', 'STUDENT HOUSING'), ('UNKNOWN', 'UNKNOWN'), ('OTHER', 'OTHER')], default='UNKNOWN', max_length=255),
        ),
        migrations.AlterField(
            model_name='laundryroomextension',
            name='legal_structure',
            field=models.CharField(choices=[('COOP', 'COOP'), ('CONDO', 'CONDO'), ('RENTAL', 'RENTAL'), ('STUDENT HOUSING', 'STUDENT HOUSING'), ('OTHER', 'OTHER'), ('UNKNOWN', 'UNKNOWN')], default='UNKNOWN', max_length=255),
        ),
    ]
