# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-11-04 09:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0046_auto_20191104_0948'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billinggroup',
            name='payees',
        ),
        migrations.AddField(
            model_name='payee',
            name='billing_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reporting.BillingGroup', verbose_name='BillingGroup'),
        ),
    ]
