# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-11-04 15:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0047_auto_20191104_0953'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingGroupEmailAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('billing_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reporting.BillingGroup')),
            ],
        ),
    ]
