# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-11-07 10:25
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0049_clientemailaddress'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeterRaise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheculed_date', models.DateField()),
                ('raise_limit', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.AddField(
            model_name='billinggroup',
            name='max_meter_raises',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meterraise',
            name='billing_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reporting.BillingGroup'),
        ),
    ]
