# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-11-07 10:29
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0050_auto_20191107_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meterraise',
            name='raise_limit',
            field=models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Dollars amount'),
        ),
    ]
