# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-11-24 11:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0052_auto_20191107_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meterraise',
            name='raise_limit',
            field=models.TextField(verbose_name='Raise Limit (Dollars amount)'),
        ),
    ]
