# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-11-24 13:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0053_auto_20191124_1120'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meterraise',
            old_name='scheculed_date',
            new_name='scheduled_date',
        ),
    ]
