# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-11-25 13:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0054_auto_20191124_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='billinggroup',
            name='lease_term_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='billinggroup',
            name='lease_term_start',
            field=models.DateField(blank=True, null=True),
        ),
    ]
