# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-03-27 21:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('reporting', '0055_auto_20191125_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='metricscache',
            name='needs_processing',
            field=models.BooleanField(default=False),
        ),
    ]
