# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-03-28 09:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('reporting', '0056_metricscache_needs_processing'),
    ]

    operations = [
        migrations.AddField(
            model_name='metricscache',
            name='ripe_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
