# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-04-06 23:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0057_metricscache_ripe_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpcomingMeterRaiseNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('completed', models.BooleanField(default=False)),
                ('meter_raise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification', to='reporting.MeterRaise')),
            ],
        ),
    ]
