# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-06-11 21:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0062_auto_20200611_2010'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoRenewHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('lease_start_date', models.DateField()),
                ('lease_end_date', models.DateField()),
                ('original', models.BooleanField()),
            ],
        ),
        migrations.AlterField(
            model_name='billinggroup',
            name='lease_term_auto_renew_length',
            field=models.IntegerField(blank=True, help_text='In Months', null=True),
        ),
        migrations.AddField(
            model_name='autorenewhistory',
            name='billing_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='autorenew_history', to='reporting.BillingGroup'),
        ),
    ]
