# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-06-11 21:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0063_auto_20200611_2100'),
    ]

    operations = [
        migrations.AddField(
            model_name='billinggroup',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
