# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-06-12 17:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0064_billinggroup_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='billinggroup',
            name='right_of_first_refusal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='billinggroup',
            name='vendor_code',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='billinggroup',
            name='lease_term_duration_days',
            field=models.IntegerField(blank=True, help_text='Leave blank for month-to-months', null=True),
        ),
        migrations.AlterField(
            model_name='billinggroup',
            name='lease_term_duration_months',
            field=models.IntegerField(blank=True, help_text='0 for month-to-months', null=True),
        ),
    ]
