# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-06-19 17:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0065_auto_20200612_1715'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ClientRevenueJobsTracker',
            new_name='ClientRevenueFullJobsTracker',
        ),
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['name']},
        ),
    ]
