# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-06-19 18:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0066_auto_20200619_1720'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientRevenueJobsTracker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobs_proccesed', models.IntegerField(blank=True, default=0, null=True)),
                ('full_report_delivered', models.BooleanField(default=False)),
                ('user_requested_email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='ClientRevenueReportJobInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('billing_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reporting.BillingGroup')),
                ('job_tracker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs_being_tracked', to='reporting.ClientRevenueJobsTracker')),
            ],
        ),
    ]
