# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-06-19 19:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import storages.backends.s3boto3


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0068_auto_20200619_1900'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientReportBasicStoredFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_file', models.FileField(blank=True, null=True, storage=storages.backends.s3boto3.S3Boto3Storage(bucket='tmp-revenue-report-files'), upload_to='')),
                ('billing_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reporting.BillingGroup')),
                ('jobs_tracker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_files', to='reporting.ClientRevenueJobsTracker')),
            ],
        ),
    ]
