# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-06-23 16:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0069_clientreportbasicstoredfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricingreportjobinfo',
            name='periods',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
