# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-06-29 17:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0070_pricingreportjobinfo_periods'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pricingreportjobinfo',
            old_name='periods',
            new_name='months',
        ),
    ]
