# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-07-11 21:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0072_auto_20200709_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricingreportjobinfo',
            name='colors',
            field=models.BooleanField(default=False),
        ),
    ]
