# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-07-24 15:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0073_pricingreportjobinfo_colors'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lessee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='billinggroup',
            name='lessee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reporting.Lessee'),
        ),
    ]
