# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-08-07 15:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0075_custompricehistory_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='description',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
