# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-08-08 18:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0076_client_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='billinggroup',
            name='operations_start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
