# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-08-22 11:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0078_clientreportbasicstoredfile_file_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildingTypeChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LegalStructureChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='metricscache',
            name='metric_type',
            field=models.CharField(blank=True, choices=[('REVENUE FUNDS', 'REVENUE FUNDS'), ('REVENUE_FUNDS_CREDIT', 'REVENUE_FUNDS_CREDIT'), ('REVENUE_FUNDS_CREDIT_PRESENT_ADD_VALUE', 'REVENUE_FUNDS_CREDIT_PRESENT_ADD_VALUE'), ('REVENUE_FUNDS_CREDIT_WEB_ADD_VALUE', 'REVENUE_FUNDS_CREDIT_WEB_ADD_VALUE'), ('REVENUE_FUNDS_CREDIT_DIRECT_VEND', 'REVENUE_FUNDS_CREDIT_DIRECT_VEND'), ('REVENUE_FUNDS_CASH', 'REVENUE_FUNDS_CASH'), ('REVENUE_FUNDS_CHECK', 'REVENUE_FUNDS_CHECK'), ('REVENUE_EARNED', 'REVENUE_EARNED'), ('FASCARD_REVENUE_FUNDS', 'FASCARD_REVENUE_FUNDS'), ('REVENUE_NUM_ZERO_DOLLAR_TRANSACTIONS', 'REVENUE_NUM_ZERO_DOLLAR_TRANSACTIONS'), ('REVENUE_NUM_NO_DATA_DAYS', 'REVENUE_NUM_NO_DATA_DAYS'), ('REFUNDS', 'REFUNDS')], max_length=255, null=True),
        ),
    ]
