# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-08-22 11:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0079_auto_20200822_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laundryroomextension',
            name='building_type',
            field=models.CharField(blank=True, choices=[('APARTMENTS', 'APARTMENTS'), ('APARTMENT BUILDING', 'APARTMENT BUILDING'), ('DORMITORY', 'DORMITORY'), ('GARDEN APARTMENTS', 'GARDEN APARTMENTS'), ('STUDENT HOUSING', 'STUDENT HOUSING'), ('UNKNOWN', 'UNKNOWN'), ('OTHER', 'OTHER')], default='UNKNOWN', max_length=255),
        ),
        migrations.AlterField(
            model_name='laundryroomextension',
            name='legal_structure',
            field=models.CharField(blank=True, choices=[('COOP', 'COOP'), ('CONDO', 'CONDO'), ('RENTAL', 'RENTAL'), ('STUDENT HOUSING', 'STUDENT HOUSING'), ('OTHER', 'OTHER'), ('UNKNOWN', 'UNKNOWN')], default='UNKNOWN', max_length=255),
        ),
    ]
