# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-08-22 11:12
from __future__ import unicode_literals

from django.db import migrations



class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0080_auto_20200822_1103'),
    ]

    operations = [
    ]
