# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-08-22 11:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion

def add_types(apps, schema_editor):
    LegalStructureChoice = apps.get_model('reporting', 'LegalStructureChoice')
    BuildingTypeChoice = apps.get_model('reporting', 'BuildingTypeChoice')
    LaundryRoomExtension = apps.get_model('reporting', 'LaundryRoomExtension')

    for ext in LaundryRoomExtension.objects.all():
        legal_structure_choice, created = LegalStructureChoice.objects.get_or_create(name=ext.legal_structure)
        building_type_choice, created = BuildingTypeChoice.objects.get_or_create(name=ext.building_type)
        ext.legal_structure_choice = legal_structure_choice
        ext.building_type_choice = building_type_choice
        ext.save()


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0081_auto_20200822_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='laundryroomextension',
            name='building_type_choice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reporting.BuildingTypeChoice'),
        ),
        migrations.AddField(
            model_name='laundryroomextension',
            name='legal_structure_choice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reporting.LegalStructureChoice'),
        ),
        migrations.RunPython(add_types)
    ]
