# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-08-22 11:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0082_auto_20200822_1119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laundryroomextension',
            name='building_type',
        ),
        migrations.RemoveField(
            model_name='laundryroomextension',
            name='legal_structure',
        ),
    ]
