# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-08-28 16:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0084_auto_20200822_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientreportfullstoredfile',
            name='report_type',
            field=models.CharField(choices=[('refunds', 'refunds'), ('transactions', 'transactions')], default='transactions', max_length=20),
        ),
    ]
