# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-12-19 09:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0088_auto_20201210_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billinggroup',
            name='allow_cashflow_refunds_deduction',
            field=models.BooleanField(default=True),
        ),
    ]
