# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2021-01-01 19:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0089_auto_20201219_0959'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientrevenuereportjobinfo',
            name='include_zero_rows',
            field=models.BooleanField(default=False),
        ),
    ]
