# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2021-01-02 14:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0090_clientrevenuereportjobinfo_include_zero_rows'),
    ]

    operations = [
        migrations.AddField(
            model_name='revenuesplitrule',
            name='min_comp_per_day',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Minimum Compensation per Day'),
        ),
    ]
