# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2021-02-16 21:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import storages.backends.s3boto3


class Migration(migrations.Migration):

    dependencies = [
        ('revenue', '0055_refundauthorizationrequest_rejected'),
        ('reporting', '0091_revenuesplitrule_min_comp_per_day'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSheetsReportJobInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('fascard_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='revenue.FascardUser')),
            ],
        ),
        migrations.CreateModel(
            name='TimeSheetsReportJobTracker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobs_proccesed', models.IntegerField(blank=True, default=0, null=True)),
                ('full_report_delivered', models.BooleanField(default=False)),
                ('user_requested_email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='TimeSheetsReportStoredFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_file', models.FileField(blank=True, null=True, storage=storages.backends.s3boto3.S3Boto3Storage(bucket='timesheets-reports'), upload_to='')),
                ('file_type', models.CharField(choices=[(('html',), ('html',)), ('pdf', 'pdf')], default=('html',), max_length=20)),
                ('fascard_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='revenue.FascardUser')),
                ('jobs_tracker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_files', to='reporting.TimeSheetsReportJobTracker')),
            ],
        ),
        migrations.AddField(
            model_name='timesheetsreportjobinfo',
            name='job_tracker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs_being_tracked', to='reporting.TimeSheetsReportJobTracker'),
        ),
    ]
