# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2021-02-17 14:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0092_auto_20210216_2152'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timesheetsreportjobinfo',
            old_name='fascard_user',
            new_name='employee',
        ),
        migrations.RenameField(
            model_name='timesheetsreportstoredfile',
            old_name='fascard_user',
            new_name='employee',
        ),
    ]
