# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2021-04-20 20:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0094_clientrevenuereportjobinfo_html_generation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billinggroup',
            name='schedule_type',
            field=models.CharField(choices=[('CONSTANT', 'Constant'), ('GROSS_REVENUE', 'Gross Revenue'), ('TIME', 'Time')], max_length=1000),
        ),
        migrations.AlterField(
            model_name='metricscache',
            name='metric_type',
            field=models.CharField(blank=True, choices=[('REVENUE FUNDS', 'REVENUE FUNDS'), ('REVENUE_FUNDS_CREDIT', 'REVENUE_FUNDS_CREDIT'), ('REVENUE_FUNDS_CREDIT_PRESENT_ADD_VALUE', 'REVENUE_FUNDS_CREDIT_PRESENT_ADD_VALUE'), ('REVENUE_FUNDS_CREDIT_WEB_ADD_VALUE', 'REVENUE_FUNDS_CREDIT_WEB_ADD_VALUE'), ('REVENUE_FUNDS_CREDIT_DIRECT_VEND', 'REVENUE_FUNDS_CREDIT_DIRECT_VEND'), ('REVENUE_FUNDS_CASH', 'REVENUE_FUNDS_CASH'), ('REVENUE_FUNDS_CHECK', 'REVENUE_FUNDS_CHECK'), ('REVENUE_EARNED', 'REVENUE_EARNED'), ('FASCARD_REVENUE_FUNDS', 'FASCARD_REVENUE_FUNDS'), ('REVENUE_NUM_ZERO_DOLLAR_TRANSACTIONS', 'REVENUE_NUM_ZERO_DOLLAR_TRANSACTIONS'), ('REVENUE_NUM_NO_DATA_DAYS', 'REVENUE_NUM_NO_DATA_DAYS'), ('REFUNDS', 'REFUNDS'), ('TRANSACTIONS_COUNT', 'TRANSACTIONS_COUNT')], max_length=255, null=True),
        ),
    ]
