# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2021-05-06 17:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0095_auto_20210420_2046'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='metricscache',
            index=models.Index(fields=['start_date'], name='metrics_cac_start_d_1ef145_idx'),
        ),
    ]
