# Generated by Django 3.1 on 2021-05-15 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roommanager', '0102_auto_20210515_1410'),
        ('reporting', '0096_auto_20210506_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billinggroupexpensetypemap',
            name='billing_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='reporting.billinggroup'),
        ),
        migrations.AlterField(
            model_name='billinggroupexpensetypemap',
            name='expense_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='reporting.expensetype'),
        ),
        migrations.AlterField(
            model_name='clientreportbasicstoredfile',
            name='billing_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='reporting.billinggroup'),
        ),
        migrations.AlterField(
            model_name='clientreportbasicstoredfile',
            name='file_type',
            field=models.CharField(choices=[('html', 'html'), ('pdf', 'pdf')], default='html', max_length=20),
        ),
        migrations.AlterField(
            model_name='clientreportbasicstoredfile',
            name='jobs_tracker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_files', to='reporting.clientrevenuejobstracker'),
        ),
        migrations.AlterField(
            model_name='clientreportfullstoredfile',
            name='jobs_tracker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_files', to='reporting.clientrevenuefulljobstracker'),
        ),
        migrations.AlterField(
            model_name='clientreportfullstoredfile',
            name='laundry_room_extension',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='reporting.laundryroomextension'),
        ),
        migrations.AlterField(
            model_name='clientrevenuefullreportjobinfo',
            name='billing_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='reporting.billinggroup'),
        ),
        migrations.AlterField(
            model_name='clientrevenuefullreportjobinfo',
            name='job_tracker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs_being_tracked', to='reporting.clientrevenuefulljobstracker'),
        ),
        migrations.AlterField(
            model_name='clientrevenuereportjobinfo',
            name='billing_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='reporting.billinggroup'),
        ),
        migrations.AlterField(
            model_name='clientrevenuereportjobinfo',
            name='job_tracker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs_being_tracked', to='reporting.clientrevenuejobstracker'),
        ),
        migrations.AlterField(
            model_name='custompricehistory',
            name='equipment_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='roommanager.equipmenttype'),
        ),
        migrations.AlterField(
            model_name='custompricehistory',
            name='laundry_room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pricing_history', to='roommanager.laundryroom'),
        ),
        migrations.AlterField(
            model_name='laundryroomextension',
            name='billing_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reporting.billinggroup'),
        ),
        migrations.AlterField(
            model_name='pricehistory',
            name='laundry_room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='roommanager.laundryroom'),
        ),
        migrations.AlterField(
            model_name='pricingperiod',
            name='laundry_room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pricing_periods', to='roommanager.laundryroom'),
        ),
        migrations.AlterField(
            model_name='pricingreportjobinfo',
            name='job_tracker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs_being_tracked', to='reporting.pricingreportjobstracker'),
        ),
        migrations.AlterField(
            model_name='pricingreportjobinfo',
            name='laundry_room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pricing_reports', to='roommanager.laundryroom'),
        ),
        migrations.AlterField(
            model_name='revenuesplitrule',
            name='revenue_split_formula',
            field=models.CharField(choices=[('PERCENT', 'Percent'), ('GENERAL_BREAKPOINT', 'General Breakpoint')], max_length=1000),
        ),
        migrations.AlterField(
            model_name='timesheetsreportjobinfo',
            name='job_tracker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs_being_tracked', to='reporting.timesheetsreportjobtracker'),
        ),
        migrations.AlterField(
            model_name='timesheetsreportstoredfile',
            name='file_type',
            field=models.CharField(choices=[('html', 'html'), ('pdf', 'pdf')], default='html', max_length=20),
        ),
        migrations.AlterField(
            model_name='timesheetsreportstoredfile',
            name='jobs_tracker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_files', to='reporting.timesheetsreportjobtracker'),
        ),
    ]
