# Generated by Django 3.1.1 on 2021-06-03 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0097_auto_20210515_1410'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='metricscache',
            name='metrics_cac_start_d_1ef145_idx',
        ),
        migrations.AddIndex(
            model_name='metricscache',
            index=models.Index(fields=['start_date', 'location_id', 'duration'], name='metrics_cac_start_d_eb856f_idx'),
        ),
    ]
