# Generated by Django 3.1.1 on 2021-06-08 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0098_auto_20210603_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billinggroupexpensetypemap',
            name='expense_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='reporting.expensetype'),
            preserve_default=False,
        ),
    ]
