# Generated by Django 3.1.1 on 2021-06-17 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0099_auto_20210608_1905'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetricsComputationWatcher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expected', models.IntegerField()),
                ('scheduled', models.IntegerField()),
                ('location_type', models.CharField(blank=True, choices=[('LAUNDRY ROOM', 'LAUNDRY ROOM'), ('MACHINE', 'MACHINE'), ('BILLING GROUP', 'BILLING GROUP')], max_length=255, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('duration_type', models.CharField(blank=True, choices=[('DAY', 'DAY'), ('MONTH', 'MONTH'), ('YEAR', 'YEAR'), ('BEFORE', 'BEFORE')], max_length=255, null=True)),
            ],
        ),
    ]
