# Generated by Django 3.1.1 on 2021-06-17 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0100_metricscomputationwatcher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metricscomputationwatcher',
            name='scheduled',
            field=models.IntegerField(default=0),
        ),
    ]
