# Generated by Django 3.1.1 on 2021-06-17 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0101_auto_20210617_2130'),
    ]

    operations = [
        migrations.RenameField(
            model_name='metricscomputationwatcher',
            old_name='duration_type',
            new_name='duration',
        ),
        migrations.RenameField(
            model_name='metricscomputationwatcher',
            old_name='location_type',
            new_name='location_level',
        ),
    ]
