# Generated by Django 3.1.1 on 2021-06-26 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roommanager', '0110_auto_20210617_2048'),
        ('reporting', '0103_nonrecurrentexpense'),
    ]

    operations = [
        migrations.AddField(
            model_name='nonrecurrentexpense',
            name='laundry_room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='roommanager.laundryroom'),
        ),
    ]
