# Generated by Django 3.1.1 on 2021-06-27 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0104_nonrecurrentexpense_laundry_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nonrecurrentexpense',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
            preserve_default=False,
        ),
    ]
