# Generated by Django 3.1.1 on 2021-06-27 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0105_auto_20210627_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientreportfullstoredfile',
            name='report_type',
            field=models.CharField(choices=[('refunds', 'refunds'), ('transactions', 'transactions'), ('nonrecurrent-expenses', 'nonrecurrent-expenses')], default='transactions', max_length=30),
        ),
    ]
