# Generated by Django 3.1.1 on 2021-07-01 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0106_auto_20210627_2133'),
    ]

    operations = [
        migrations.AddField(
            model_name='nonrecurrentexpense',
            name='expense_type',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
