# Generated by Django 3.1.1 on 2021-07-18 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0107_nonrecurrentexpense_expense_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='billinggroup',
            name='additional_insureds',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
