# Generated by Django 3.1.1 on 2021-11-28 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0109_outoforderreportlog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientrevenuefulljobstracker',
            old_name='jobs_proccesed',
            new_name='jobs_processed',
        ),
        migrations.RenameField(
            model_name='clientrevenuejobstracker',
            old_name='jobs_proccesed',
            new_name='jobs_processed',
        ),
        migrations.RenameField(
            model_name='timesheetsreportjobtracker',
            old_name='jobs_proccesed',
            new_name='jobs_processed',
        ),
        migrations.AlterField(
            model_name='clientreportfullstoredfile',
            name='report_type',
            field=models.CharField(choices=[('refunds', 'refunds'), ('transactions', 'transactions'), ('nonrecurrent-expenses', 'nonrecurrent-expenses'), ('error', 'error')], default='transactions', max_length=30),
        ),
    ]
