# Generated by Django 3.1.1 on 2021-12-18 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0110_auto_20211128_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientrevenuefulljobstracker',
            name='user_requested_email',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='clientrevenuejobstracker',
            name='user_requested_email',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='pricingreportjobstracker',
            name='user_requested_email',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='timesheetsreportjobtracker',
            name='user_requested_email',
            field=models.CharField(max_length=200),
        ),
    ]
