# Generated by Django 3.1.1 on 2021-12-23 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0111_auto_20211218_2319'),
    ]

    operations = [
        migrations.AddField(
            model_name='billinggroupexpensetypemap',
            name='pass_to_client',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='nonrecurrentexpense',
            name='pass_to_client_share',
            field=models.BooleanField(default=False),
        ),
    ]
