# Generated by Django 3.1.1 on 2022-06-09 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0112_auto_20211223_2108'),
    ]

    operations = [
        migrations.AddField(
            model_name='billinggroup',
            name='payment_method',
            field=models.CharField(choices=[('ach', 'ach'), ('check', 'check'), ('unknown', 'unknown')], default='unknown', max_length=100),
        ),
    ]
