# Generated by Django 3.1.1 on 2022-07-04 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0114_pricingreportjobinfo_revenue_data_granularity'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoredFascardToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_token', models.CharField(max_length=100)),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
