# Generated by Django 3.1.1 on 2022-08-24 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0116_auto_20220704_1151'),
    ]

    operations = [
    ]
