# Generated by Django 3.1.1 on 2022-11-21 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0117_auto_20220824_2048'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientrevenuereportjobinfo',
            name='fully_processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clientrevenuereportjobinfo',
            name='invoice_amount',
            field=models.TextField(blank=True, null=True),
        ),
    ]
