# Generated by Django 3.1.1 on 2022-11-21 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0118_auto_20221121_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientrevenuereportjobinfo',
            name='invoice_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
