# Generated by Django 3.1.1 on 2022-11-22 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0119_auto_20221121_2219'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientreportbasicstoredfile',
            name='job_info',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='reporting.clientrevenuereportjobinfo'),
        ),
    ]
