# Generated by Django 3.1.1 on 2022-12-21 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0122_auto_20221221_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='laundryroomextension',
            name='zip_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
