# Generated by Django 3.1.1 on 2022-12-26 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0123_laundryroomextension_zip_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricingperiod',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
