# Generated by Django 3.1.1 on 2023-05-31 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roommanager', '0152_auto_20230511_1921'),
        ('reporting', '0125_auto_20230108_2236'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnomalyDetectionJobTracker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AnomalyDetectionJobInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg', models.CharField(max_length=300)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('job_tracker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reporting.anomalydetectionjobtracker')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roommanager.machine')),
            ],
        ),
    ]
