# Generated by Django 3.1.1 on 2023-05-31 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0126_anomalydetectionjobinfo_anomalydetectionjobtracker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anomalydetectionjobinfo',
            name='job_tracker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs_being_tracked', to='reporting.anomalydetectionjobtracker'),
        ),
    ]
