# Generated by Django 3.1.1 on 2023-05-31 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0127_auto_20230531_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='anomalydetectionjobtracker',
            name='full_report_delivered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='anomalydetectionjobtracker',
            name='jobs_processed',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='anomalydetectionjobtracker',
            name='user_requested_email',
            field=models.CharField(default='suricatadev@gmail.com', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='anomalydetectionjobinfo',
            name='msg',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
