# Generated by Django 3.1.1 on 2023-05-31 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0128_auto_20230531_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='anomalydetectionjobinfo',
            name='anomaly_detected',
            field=models.BooleanField(default=False),
        ),
    ]
