# Generated by Django 3.1.1 on 2023-06-17 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0129_anomalydetectionjobinfo_anomaly_detected'),
    ]

    operations = [
        migrations.AddField(
            model_name='anomalydetectionjobinfo',
            name='date_range',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='anomalydetectionjobinfo',
            name='days_window',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]