# Generated by Django 3.1.1 on 2023-06-17 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0130_auto_20230617_0027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anomalydetectionjobinfo',
            name='date_range',
            field=models.DateField(blank=True, null=True),
        ),
    ]