# Generated by Django 3.1.1 on 2023-06-21 10:18

from django.db import migrations, models
import storages.backends.s3boto3


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0131_auto_20230617_0035'),
    ]

    operations = [
        migrations.AddField(
            model_name='anomalydetectionjobinfo',
            name='report_file_graphs',
            field=models.FileField(blank=True, null=True, storage=storages.backends.s3boto3.S3Boto3Storage(bucket='anomaly-detection-report-graphs'), upload_to=''),
        ),
        migrations.AlterField(
            model_name='anomalydetectionjobinfo',
            name='date_range',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]