# Generated by Django 3.1.1 on 2023-06-21 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0131_auto_20230617_0035'),
    ]

    operations = [
        migrations.AddField(
            model_name='anomalydetectionjobinfo',
            name='processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='anomalydetectionjobinfo',
            name='date_range',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]