# Generated by Django 3.1.1 on 2023-06-21 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0132_auto_20230621_1018'),
        ('reporting', '0132_auto_20230621_1228'),
    ]

    operations = [
    ]