# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-10 19:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('outoforder', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='slotstateerror',
            unique_together=set([('slot_state', 'error_type')]),
        ),
    ]
