# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-21 12:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outoforder', '0002_auto_20170410_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='slotstate',
            name='mlvmacherror_description',
            field=models.IntegerField(blank=True, choices=[(0, b'Machine OK'), (1, b'Unable to communicate with machine'), (2, b'Machine leaking water'), (3, b'Machine stuck in cycle'), (4, b'Machine not filling'), (5, b'Machine not draining'), (6, b'Machine not heating'), (7, b'Machine door problem'), (100, b'Part or all of config was rejected'), (101, b'One or more messages timed out or were rejected'), (999, b'Unknown machine problem'), (1000, b'Machine code indicates error')], default=0, null=True),
        ),
        migrations.AddField(
            model_name='slotstate',
            name='slot_status_text',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
