# Generated by Django 3.1 on 2021-05-15 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('roommanager', '0102_auto_20210515_1410'),
        ('reporting', '0097_auto_20210515_1410'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('report_type', models.CharField(choices=[('internal_report', 'internal_report'), ('client_report', 'client_report'), ('client_full_lowlevel_report', 'client_full_lowlevel_report')], max_length=150)),
                ('report_id', models.IntegerField()),
                ('arn', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='InternalReportConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('time_grouping', models.CharField(choices=[('DAY', 'DAY'), ('MONTH', 'MONTH'), ('YEAR', 'YEAR'), ('BEFORE', 'BEFORE')], max_length=20)),
                ('location_grouping', models.CharField(choices=[('DAY', 'DAY'), ('MONTH', 'MONTH'), ('YEAR', 'YEAR'), ('BEFORE', 'BEFORE')], max_length=20)),
                ('revenue_rule', models.CharField(choices=[('REVENUE FUNDS', 'REVENUE FUNDS'), ('REVENUE_FUNDS_CREDIT', 'REVENUE_FUNDS_CREDIT'), ('REVENUE_FUNDS_CREDIT_PRESENT_ADD_VALUE', 'REVENUE_FUNDS_CREDIT_PRESENT_ADD_VALUE'), ('REVENUE_FUNDS_CREDIT_WEB_ADD_VALUE', 'REVENUE_FUNDS_CREDIT_WEB_ADD_VALUE'), ('REVENUE_FUNDS_CREDIT_DIRECT_VEND', 'REVENUE_FUNDS_CREDIT_DIRECT_VEND'), ('REVENUE_FUNDS_CASH', 'REVENUE_FUNDS_CASH'), ('REVENUE_FUNDS_CHECK', 'REVENUE_FUNDS_CHECK'), ('REVENUE_EARNED', 'REVENUE_EARNED'), ('FASCARD_REVENUE_FUNDS', 'FASCARD_REVENUE_FUNDS'), ('REVENUE_NUM_ZERO_DOLLAR_TRANSACTIONS', 'REVENUE_NUM_ZERO_DOLLAR_TRANSACTIONS'), ('REVENUE_NUM_NO_DATA_DAYS', 'REVENUE_NUM_NO_DATA_DAYS'), ('REFUNDS', 'REFUNDS'), ('TRANSACTIONS_COUNT', 'TRANSACTIONS_COUNT')], max_length=50)),
                ('active_only', models.BooleanField(default=False)),
                ('exclude_zero_rows', models.BooleanField(default=False)),
                ('sort_by', models.CharField(choices=[('fascard_code', 'Fascard Code'), ('alphabetical', 'Alphabetical')], max_length=20)),
                ('delivery_method', models.CharField(choices=[('download', 'Direct Download'), ('email', 'Email')], max_length=15)),
                ('email', models.CharField(max_length=100)),
                ('cron_expression', models.CharField(max_length=20)),
                ('billing_groups', models.ManyToManyField(blank=True, null=True, related_name='billing_groups', to='reporting.BillingGroup')),
                ('rooms', models.ManyToManyField(blank=True, null=True, related_name='rooms', to='roommanager.LaundryRoom')),
            ],
        ),
    ]
