# Generated by Django 3.1.1 on 2021-05-16 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_auto_20210516_1119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventrule',
            name='report_id',
        ),
        migrations.RemoveField(
            model_name='eventrule',
            name='report_type',
        ),
        migrations.AddField(
            model_name='eventrule',
            name='target_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='internalreportconfig',
            name='event_rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reports.eventrule'),
        ),
    ]
