# Generated by Django 3.1.1 on 2021-05-16 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_auto_20210516_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internalreportconfig',
            name='location_grouping',
            field=models.CharField(choices=[('LAUNDRY ROOM', 'LAUNDRY ROOM'), ('MACHINE', 'MACHINE'), ('BILLING GROUP', 'BILLING GROUP')], max_length=20),
        ),
    ]
