# Generated by Django 3.1.1 on 2021-05-17 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0097_auto_20210515_1410'),
        ('reports', '0006_auto_20210517_1136'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientFullRevenueReportConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_units_lookback', models.IntegerField(default=1)),
                ('time_units', models.CharField(choices=[('days', 'days'), ('weeks', 'weeks'), ('months', 'months'), ('years', 'years')], default='months', max_length=30)),
                ('email', models.CharField(max_length=100)),
                ('cron_expression', models.CharField(max_length=20)),
                ('include_zero_rows', models.BooleanField(default=False)),
                ('billing_groups', models.ManyToManyField(blank=True, null=True, to='reporting.BillingGroup')),
                ('event_rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reports.eventrule')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
