# Generated by Django 3.1.1 on 2021-05-17 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0008_auto_20210517_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentpaidreportconfig',
            name='metric',
            field=models.CharField(choices=[('client_share', 'Rent Payment Amount'), ('rent_percent_revenue', 'Rent as percentage of gross revenue'), ('aces_after_rent', 'Aces net revenue after rent'), ('acesnet_percentage_revenue', 'Aces net revenue after rent as percentage of gross revenue')], max_length=50),
        ),
    ]
