# Generated by Django 3.1.1 on 2021-05-17 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('revenue', '0059_auto_20210515_1410'),
        ('reports', '0009_auto_20210517_1346'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionReportConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_units_lookback', models.IntegerField(default=1)),
                ('time_units', models.CharField(choices=[('days', 'days'), ('weeks', 'weeks'), ('months', 'months'), ('years', 'years')], default='months', max_length=30)),
                ('email', models.CharField(max_length=100)),
                ('cron_expression', models.CharField(max_length=20)),
                ('report_type', models.CharField(choices=[('checks_deposits', 'Checks Deposits'), ('auto_reloads', 'Auto Reloads'), ('web_value_adds', 'Web Value Adds'), ('employee_adds', 'Employees ---- value adds to employee accounts'), ('employee_activity', 'Employees ---- machine starts by employees'), ('employee_timesheet', 'Employees ---- Timesheet'), ('customer_admin_ajusts', 'Employees ---- Admin adjust to customers')], max_length=100)),
                ('employee', models.ManyToManyField(blank=True, to='revenue.FascardUser')),
                ('event_rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reports.eventrule')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
