# Generated by Django 3.1.1 on 2021-05-17 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0010_transactionreportconfig'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactionreportconfig',
            old_name='employee',
            new_name='employees',
        ),
    ]
