# Generated by Django 3.1.1 on 2021-05-17 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0012_auto_20210517_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internalreportconfig',
            name='event_rule',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reports.eventrule'),
        ),
    ]
