# Generated by Django 3.1.1 on 2021-06-10 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0013_auto_20210517_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientfullrevenuereportconfig',
            name='cron_expression',
            field=models.CharField(help_text='Cron expression must be 6 fields long / No seconds needed', max_length=20),
        ),
        migrations.AlterField(
            model_name='clientrevenuereportconfig',
            name='cron_expression',
            field=models.CharField(help_text='Cron expression must be 6 fields long / No seconds needed', max_length=20),
        ),
        migrations.AlterField(
            model_name='rentpaidreportconfig',
            name='cron_expression',
            field=models.CharField(help_text='Cron expression must be 6 fields long / No seconds needed', max_length=20),
        ),
        migrations.AlterField(
            model_name='transactionreportconfig',
            name='cron_expression',
            field=models.CharField(help_text='Cron expression must be 6 fields long / No seconds needed', max_length=20),
        ),
    ]
