# Generated by Django 3.1.1 on 2021-06-11 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0014_auto_20210610_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientfullrevenuereportconfig',
            name='event_rule',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reports.eventrule'),
        ),
        migrations.AlterField(
            model_name='clientrevenuereportconfig',
            name='event_rule',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reports.eventrule'),
        ),
        migrations.AlterField(
            model_name='internalreportconfig',
            name='event_rule',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reports.eventrule'),
        ),
        migrations.AlterField(
            model_name='rentpaidreportconfig',
            name='event_rule',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reports.eventrule'),
        ),
        migrations.AlterField(
            model_name='transactionreportconfig',
            name='event_rule',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reports.eventrule'),
        ),
    ]
