# Generated by Django 3.1.1 on 2021-12-25 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0016_auto_20210704_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='internalreportconfig',
            name='include_all_billing_groups',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='internalreportconfig',
            name='include_all_rooms',
            field=models.BooleanField(default=False),
        ),
    ]
