# Generated by Django 3.1.1 on 2021-12-25 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0017_auto_20211225_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionreportconfig',
            name='last_activity_lookback',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='transactionreportconfig',
            name='last_activity_lookback_time_units',
            field=models.CharField(choices=[('days', 'days'), ('weeks', 'weeks'), ('months', 'months'), ('years', 'years')], default='months', max_length=30),
        ),
    ]
