# Generated by Django 3.1.1 on 2022-05-06 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0019_auto_20211225_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventrule',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
