# Generated by Django 3.1.1 on 2023-05-14 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0020_eventrule_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientrevenuereportconfig',
            name='include_inactive_billing_groups',
            field=models.BooleanField(default=False),
        ),
    ]
