'''
Created on Mar 28, 2017

@author: Duong
'''
class JobType(): 
    MACHINE_PURCHASE = 'MACHINE PURCHASE'
    MACHINE_REPAIR = 'MACHINE REPAIR'
    MACHINE_INSTALLATION = 'MACHINE INSTALLATION'
    PLUMBING = 'PLUMBING'
    ELECTRICAL_WORK = 'ELECTRICAL WORK'
    
    CHOICES = ((MACHINE_PURCHASE,MACHINE_PURCHASE),(MACHINE_REPAIR,MACHINE_REPAIR),
                (MACHINE_INSTALLATION,MACHINE_INSTALLATION),(PLUMBING,PLUMBING),
                (ELECTRICAL_WORK,ELECTRICAL_WORK))


class JobStatus():
    CREATED = 'CREATED'
    IN_PROGRESS = 'IN PROGRESS'
    CLOSED = 'CLOSED'

    CHOICES = ((CREATED,'CREATED'),(IN_PROGRESS,'IN_PROGRESS'),(CLOSED,'CLOSED'))


class EmploymentType():
    CONTRACTOR = 'CONTRACTOR'
    EMPLOYEE = 'EMPLOYEE'
    
    CHOICES = ((CONTRACTOR,CONTRACTOR),(EMPLOYEE,EMPLOYEE))


class LineItemType():
    LABOR = 'LABOR'
    PART = 'PART'
    
    CHOICES = ((LABOR,LABOR),(PART,PART))


class LineItemStatus():
    CREATED = 'CREATED'
    IN_PROGRESS = 'IN PROGRESS'
    CLOSED = 'CLOSED'

    CHOICES = ((CREATED,'CREATED'),(IN_PROGRESS,'IN_PROGRESS'),(CLOSED,'CLOSED'))
