# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-08-22 18:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upkeep', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storedupkeeptoken',
            old_name='timestamp',
            new_name='saved_at',
        ),
    ]
