'''
Created on Apr 5, 2017

@author: Thomas
'''

class MachineStateType(): #NB: States -5 to -1 need to be kept in line with Slot Error Types
    FIRMWARE_DOWNLOADING_READER = -10
    FIRMWARE_DOWNLOADING_SATELLITE = -9
    FIRMWARE_DOES_NOT_EXIST = -8
    DUPLICATE = -11
    TEST_STATE = -6
    UNKNOWN = -5
    DIAGNOSTIC = -4
    DISABLED = -3
    ERROR = -2
    OFFLINE = -1
    IDLE = 0
    RUNNING = 1
    CHOICES = ((DIAGNOSTIC,DIAGNOSTIC),(DISABLED,DISABLED),(OFFLINE,OFFLINE),(IDLE,IDLE),(RUNNING,RUNNING),(ERROR,ERROR),
                      (UNKNOWN,UNKNOWN),(TEST_STATE,TEST_STATE))
    
class SlotErrorType(): #NB: States -5 to -1 need to be kept in line with MachineStateType
    UNKNOWN = -5
    DIAGNOSTIC = -4
    DISABLED = -3
    ERROR = -2
    OFFLINE = -1
    LONG_IDLE = -6
    LONG_RUNNING = -7 
    SHORT_RUNNING = -8 
    FLICKERING = -9
    LONG_TRANSACTION_GAP = -10
    DUPLICATE = -11
    CHOICES = ((UNKNOWN,'UNKNOWN'),(DIAGNOSTIC,'DIAGNOSTIC'),(DISABLED,'DISABLED'),
               (ERROR,'ERROR'),(OFFLINE,'OFFLINE'),(LONG_IDLE,'LONG_IDLE'),(LONG_RUNNING,'LONG_RUNNING'),(SHORT_RUNNING,'SHORT_RUNNING'),
               (FLICKERING,'FLICKERING'),(LONG_TRANSACTION_GAP,LONG_TRANSACTION_GAP))
    FASCAR_ERRORS = [UNKNOWN,DIAGNOSTIC,DISABLED,ERROR,OFFLINE]